export interface SubChapter {
  id: number;
  title: string;
  focus: string;
  example: string;

  w5h1: string;
}

export interface Chapter {
  id: number;
  title: string;
  subtitle: string;
  tagline: string;
  description: string;
  subChapters: SubChapter[];
}

export const chapters: Chapter[] = [
  {
    id: 1,
    title: "Ekonomi",
    subtitle: "Perputaran Value",
    tagline: '"Kenapa harga cabai naik saat lebaran, dan kenapa itu bukan kebetulan."',
    description:
      'Pernahkah kamu ke pasar saat H-2 Lebaran dan menyadari harga cabai serta daging sapi tiba-tiba meroket? Atau bingung kenapa kadang gaji terasa cepat habis padahal kamu tidak belanja barang mewah? Di bab ini, kita akan membongkar "mesin tak terlihat" yang menggerakkan keseharian kita—mulai dari pasar tradisional hingga layar smartphone kamu.',
    subChapters: [
      {
        id: 1,
        title: "Uang",
        focus: "Apa itu nilai ekonomi?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 2,
        title: "Barter",
        focus: "Apa itu inflasi?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 3,
        title: "Perputaran",
        focus: "Apa itu pasar?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 4,
        title: "Kelangkaan",
        focus: "Apa itu kebijakan fiskal?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 5,
        title: "Struktur",
        focus: "Apa itu kebijakan moneter?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 6,
        title: "Karakteristik",
        focus: "Apa itu indikator ekonomi?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 7,
        title: "Tujuan",
        focus: "Siapa pelaku pasar?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 8,
        title: "Urgensi",
        focus: "Siapa yang menentukan kebijakan ekonomi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 9,
        title: "Manfaat Makro",
        focus: "Siapa yang paling terdampak inflasi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 10,
        title: "Manfaat Mikro",
        focus: "Siapa produsen dalam rantai ekonomi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 11,
        title: "Resiko",
        focus: "Siapa konsumen dalam sistem ekonomi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 12,
        title: "Kontribusi",
        focus: "Siapa regulator ekonomi suatu negara?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 13,
        title: "Pelaku Utama",
        focus: "Kapan resesi terjadi?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 14,
        title: "Pihak Pendukung",
        focus: "Kapan kebijakan moneter diubah?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 15,
        title: "Penerima Manfaat",
        focus: "Kapan inflasi dianggap tidak sehat?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 16,
        title: "Regulator / Pengawas",
        focus: "Kapan siklus bisnis berulang?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 17,
        title: "Kompetensi SDM",
        focus: "Kapan krisis ekonomi menyebar ke negara lain?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 18,
        title: "Pemimpin Puncak",
        focus: "Kapan indikator ekonomi dirilis ke publik?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 19,
        title: "Ruang Lingkup Internal",
        focus: "Dimana pasar tenaga kerja terbentuk?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 20,
        title: "Ruang Lingkup Eksternal",
        focus: "Dimana ekonomi informal berkembang?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 21,
        title: "Lokus Fisik",
        focus: "Dimana pusat industri suatu negara berada?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 22,
        title: "Lokus Digital",
        focus: "Dimana ketimpangan ekonomi paling terasa?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 23,
        title: "Jangkauan Ekosistem",
        focus: "Dimana ekonomi digital tumbuh paling cepat?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 24,
        title: "Hambatan Struktural",
        focus: "Dimana kebijakan ekonomi dirumuskan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 25,
        title: "Fase Inisiasi",
        focus: "Mengapa harga barang naik-turun?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 26,
        title: "Fase Pertumbuhan",
        focus: "Mengapa negara butuh kebijakan fiskal?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 27,
        title: "Fase Kematangan",
        focus: "Mengapa ekonomi mengalami siklus naik-turun?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 28,
        title: "Fase Krisis",
        focus: "Mengapa distribusi pendapatan tidak merata?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 29,
        title: "Siklus Kritis",
        focus: "Mengapa ekonomi global saling terhubung?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 30,
        title: "Horizon Waktu",
        focus: "Mengapa daya beli masyarakat berubah-ubah?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 31,
        title: "Mekanisme Dasar",
        focus: "Bagaimana harga pasar terbentuk?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 32,
        title: "Metodologi Pilihan",
        focus: "Bagaimana bank sentral mengendalikan inflasi?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 33,
        title: "Kerangka Tata Kelola",
        focus: "Bagaimana produksi memengaruhi harga barang?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 34,
        title: "Infrastruktur & Tools",
        focus: "Bagaimana ekonomi suatu negara diukur?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 35,
        title: "Strategi Implementasi",
        focus: "Bagaimana perilaku konsumen memengaruhi ekonomi?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 36,
        title: "Metrik & Evaluasi",
        focus: "Bagaimana krisis ekonomi bisa dicegah?",
        example: "",
        w5h1: "HOW",
      },
    ],
  },
  {
    id: 2,
    title: "Statistik",
    subtitle: "Pendataan Value",
    tagline: '"Bagaimana sesuatu yang belum ada, tercipta dan bernilai"',
    description: "Cerita produk yang dulu dianggap mustahil, kini jadi kebutuhan sehari-hari",
    subChapters: [
      {
        id: 1,
        title: "Definisi",
        focus: "Apa itu design thinking?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 2,
        title: "Objek",
        focus: "Apa itu action research?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 3,
        title: "Klasifikasi",
        focus: "Apa itu open innovation?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 4,
        title: "Komponen",
        focus: "Apa itu R&D?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 5,
        title: "Struktur",
        focus: "Apa itu prototipe/MVP?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 6,
        title: "Karakteristik",
        focus: "Apa itu kekayaan intelektual?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 7,
        title: "Tujuan",
        focus: "Siapa yang berperan dalam triple helix inovasi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 8,
        title: "Urgensi",
        focus: "Siapa yang melakukan penelitian dan pengembangan?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 9,
        title: "Manfaat Makro",
        focus: "Siapa yang melindungi hak cipta/paten suatu ide?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 10,
        title: "Manfaat Mikro",
        focus: "Siapa yang menjadi pengadopsi awal (early adopter) inovasi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 11,
        title: "Resiko",
        focus: "Siapa yang terlibat dalam manajemen inovasi organisasi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 12,
        title: "Kontribusi",
        focus: "Siapa yang menulis karya ilmiah sebagai dokumentasi temuan?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 13,
        title: "Pelaku Utama",
        focus: "Kapan suatu ide dianggap layak dikembangkan lebih lanjut?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 14,
        title: "Pihak Pendukung",
        focus: "Kapan prototipe/MVP sebaiknya diuji ke pasar?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 15,
        title: "Penerima Manfaat",
        focus: "Kapan disrupsi biasanya terjadi dalam suatu industri?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 16,
        title: "Regulator / Pengawas",
        focus: "Kapan suatu inovasi dianggap berhasil terdifusi ke masyarakat?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 17,
        title: "Kompetensi SDM",
        focus: "Kapan paten harus segera didaftarkan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 18,
        title: "Pemimpin Puncak",
        focus: "Kapan penelitian ilmiah dianggap valid untuk dipublikasikan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 19,
        title: "Ruang Lingkup Internal",
        focus: "Dimana pusat riset dan pengembangan biasanya berada?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 20,
        title: "Ruang Lingkup Eksternal",
        focus: "Dimana ide-ide inovatif paling sering muncul?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 21,
        title: "Lokus Fisik",
        focus: "Dimana kolaborasi triple helix paling efektif diterapkan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 22,
        title: "Lokus Digital",
        focus: "Dimana inovasi sosial paling dibutuhkan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 23,
        title: "Jangkauan Ekosistem",
        focus: "Dimana kekayaan intelektual paling rentan dicuri?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 24,
        title: "Hambatan Struktural",
        focus: "Dimana metode action research sering diterapkan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 25,
        title: "Fase Inisiasi",
        focus: "Mengapa organisasi perlu mengelola inovasi secara sistematis?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 26,
        title: "Fase Pertumbuhan",
        focus: "Mengapa pendatang baru bisa menumbangkan pemain lama?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 27,
        title: "Fase Kematangan",
        focus: "Mengapa sebagian orang lambat mengadopsi hal baru?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 28,
        title: "Fase Krisis",
        focus: "Mengapa ide perlu dilindungi lewat kekayaan intelektual?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 29,
        title: "Siklus Kritis",
        focus: "Mengapa penelitian ilmiah perlu didokumentasikan dan dipublikasikan?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 30,
        title: "Horizon Waktu",
        focus: "Mengapa inovasi berkelanjutan penting bagi masa depan?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 31,
        title: "Mekanisme Dasar",
        focus: "Bagaimana ide baru bisa muncul dan berkembang?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 32,
        title: "Metodologi Pilihan",
        focus: "Bagaimana metode ilmiah menguji validitas suatu ide?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 33,
        title: "Kerangka Tata Kelola",
        focus: "Bagaimana prototipe diuji sebelum modal besar dikeluarkan?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 34,
        title: "Infrastruktur & Tools",
        focus: "Bagaimana difusi inovasi terjadi di masyarakat?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 35,
        title: "Strategi Implementasi",
        focus: "Bagaimana manajemen industri mengelola proses produksi secara efisien?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 36,
        title: "Metrik & Evaluasi",
        focus: "Bagaimana inovasi sosial menciptakan nilai bagi masyarakat?",
        example: "",
        w5h1: "HOW",
      },
    ],
  },
  {
    id: 3,
    title: "Manajemen",
    subtitle: "Pengelolaan Value",
    tagline: '"Kenapa produk bagus bisa gagal, dan produk biasa bisa laris."',
    description:
      "Pernahkah kamu melihat bisnis kecil yang tiba-tiba ramai, lalu sebulan kemudian sepi dan terpaksa tutup? Atau heran kenapa produk yang biasa saja bisa laris manis, sementara yang inovatif malah gagal? Di bab ini, kita akan mempelajari dinamika bisnis—mulai dari bagaimana produk diciptakan, dijual, hingga cara bertahan di tengah persaingan pasar yang kejam.",
    subChapters: [
      {
        id: 1,
        title: "Definisi",
        focus: "Apa itu model bisnis?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 2,
        title: "Objek",
        focus: "Apa itu strategi bersaing?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 3,
        title: "Klasifikasi",
        focus: "Apa itu siklus hidup produk?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 4,
        title: "Komponen",
        focus: "Apa itu customer experience?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 5,
        title: "Struktur",
        focus: "Apa itu tata kelola bisnis (GRC)?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 6,
        title: "Karakteristik",
        focus: "Apa itu franchise?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 7,
        title: "Tujuan",
        focus: "Siapa target pelanggan suatu bisnis?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 8,
        title: "Urgensi",
        focus: "Siapa pesaing utama dalam industri?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 9,
        title: "Manfaat Makro",
        focus: "Siapa mitra strategis bisnis?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 10,
        title: "Manfaat Mikro",
        focus: "Siapa pemangku kepentingan (stakeholder) bisnis?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 11,
        title: "Resiko",
        focus: "Siapa yang bertanggung jawab atas tata kelola bisnis?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 12,
        title: "Kontribusi",
        focus: "Siapa pelaku wirausaha?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 13,
        title: "Pelaku Utama",
        focus: "Kapan bisnis harus melakukan ekspansi?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 14,
        title: "Pihak Pendukung",
        focus: "Kapan produk sebaiknya diluncurkan ke pasar?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 15,
        title: "Penerima Manfaat",
        focus: "Kapan bisnis perlu berganti strategi?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 16,
        title: "Regulator / Pengawas",
        focus: "Kapan waktu tepat menjalin kemitraan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 17,
        title: "Kompetensi SDM",
        focus: "Kapan krisis bisnis biasanya muncul?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 18,
        title: "Pemimpin Puncak",
        focus: "Kapan bisnis siap go international?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 19,
        title: "Ruang Lingkup Internal",
        focus: "Dimana bisnis menentukan lokasi operasinya?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 20,
        title: "Ruang Lingkup Eksternal",
        focus: "Dimana produk dijual ke pelanggan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 21,
        title: "Lokus Fisik",
        focus: "Dimana kompetisi bisnis paling ketat?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 22,
        title: "Lokus Digital",
        focus: "Dimana digitalisasi bisnis paling terasa dampaknya?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 23,
        title: "Jangkauan Ekosistem",
        focus: "Dimana rantai nilai bisnis menghasilkan untung terbesar?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 24,
        title: "Hambatan Struktural",
        focus: "Dimana bisnis internasional menghadapi tantangan terbesar?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 25,
        title: "Fase Inisiasi",
        focus: "Mengapa produk bagus bisa gagal di pasar?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 26,
        title: "Fase Pertumbuhan",
        focus: "Mengapa pelanggan setia lebih berharga dari pelanggan baru?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 27,
        title: "Fase Kematangan",
        focus: "Mengapa bisnis perlu diversifikasi?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 28,
        title: "Fase Krisis",
        focus: "Mengapa layanan buruk merusak reputasi produk?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 29,
        title: "Siklus Kritis",
        focus: "Mengapa etika bisnis penting dijaga?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 30,
        title: "Horizon Waktu",
        focus: "Mengapa sebagian bisnis memilih model franchise?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 31,
        title: "Mekanisme Dasar",
        focus: "Bagaimana bisnis menciptakan model yang menghasilkan uang?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 32,
        title: "Metodologi Pilihan",
        focus: "Bagaimana strategi bersaing disusun?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 33,
        title: "Kerangka Tata Kelola",
        focus: "Bagaimana bisnis mengelola operasional sehari-hari?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 34,
        title: "Infrastruktur & Tools",
        focus: "Bagaimana bisnis bertahan di masa krisis?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 35,
        title: "Strategi Implementasi",
        focus: "Bagaimana bisnis membangun loyalitas pelanggan?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 36,
        title: "Metrik & Evaluasi",
        focus: "Bagaimana bisnis kecil naik kelas jadi besar?",
        example: "",
        w5h1: "HOW",
      },
    ],
  },
  {
    id: 4,
    title: "Komunikasi",
    subtitle: "Penyampaian Value",
    tagline: '"Kenapa pesan yang sama bisa dipahami beda oleh tiap orang"',
    description: "Cerita miskomunikasi yang berujung masalah besar",
    subChapters: [
      {
        id: 1,
        title: "Definisi",
        focus: "Apa itu rantai pasok (supply chain)?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 2,
        title: "Objek",
        focus: "Apa itu pergudangan?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 3,
        title: "Klasifikasi",
        focus: "Apa itu freight forwarding?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 4,
        title: "Komponen",
        focus: "Apa itu cold chain?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 5,
        title: "Struktur",
        focus: "Apa itu cross-docking?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 6,
        title: "Karakteristik",
        focus: "Apa itu logistik berkelanjutan?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 7,
        title: "Tujuan",
        focus: "Siapa yang mengelola armada kendaraan logistik?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 8,
        title: "Urgensi",
        focus: "Siapa penyedia jasa logistik pihak ketiga (3PL)?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 9,
        title: "Manfaat Makro",
        focus: "Siapa yang bertanggung jawab atas bea cukai?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 10,
        title: "Manfaat Mikro",
        focus: "Siapa yang menentukan rute pengiriman?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 11,
        title: "Resiko",
        focus: "Siapa yang menangani distribusi bantuan bencana?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 12,
        title: "Kontribusi",
        focus: "Siapa aktor utama dalam rantai pasok suatu produk?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 13,
        title: "Pelaku Utama",
        focus: "Kapan barang harus disimpan di gudang vs langsung didistribusikan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 14,
        title: "Pihak Pendukung",
        focus: "Kapan persediaan dianggap kritis (kosong/menumpuk)?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 15,
        title: "Penerima Manfaat",
        focus: "Kapan proses ekspor-impor memerlukan waktu paling lama?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 16,
        title: "Regulator / Pengawas",
        focus: "Kapan teknologi tracking digunakan dalam pengiriman?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 17,
        title: "Kompetensi SDM",
        focus: "Kapan logistik bencana harus segera bergerak?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 18,
        title: "Pemimpin Puncak",
        focus: "Kapan barang berbahaya butuh penanganan khusus?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 19,
        title: "Ruang Lingkup Internal",
        focus: "Dimana barang disimpan sebelum didistribusikan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 20,
        title: "Ruang Lingkup Eksternal",
        focus: "Dimana proses bea cukai dilakukan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 21,
        title: "Lokus Fisik",
        focus: "Dimana cold chain paling dibutuhkan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 22,
        title: "Lokus Digital",
        focus: "Dimana last-mile delivery paling menantang?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 23,
        title: "Jangkauan Ekosistem",
        focus: "Dimana pelabuhan berperan dalam rantai logistik?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 24,
        title: "Hambatan Struktural",
        focus: "Dimana logistik e-commerce berbeda dari logistik konvensional?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 25,
        title: "Fase Inisiasi",
        focus: "Mengapa barang di kota besar cenderung lebih murah?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 26,
        title: "Fase Pertumbuhan",
        focus: "Mengapa stok kosong dan menumpuk sama-sama merugikan?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 27,
        title: "Fase Kematangan",
        focus: "Mengapa perusahaan menyerahkan logistik ke pihak ketiga?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 28,
        title: "Fase Krisis",
        focus: "Mengapa kemasan penting selain untuk melindungi barang?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 29,
        title: "Siklus Kritis",
        focus: "Mengapa logistik hijau menjadi isu penting?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 30,
        title: "Horizon Waktu",
        focus: "Mengapa distribusi vaksin butuh penanganan khusus?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 31,
        title: "Mekanisme Dasar",
        focus: "Bagaimana barang bisa sampai ke rumah pelanggan dalam sehari?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 32,
        title: "Metodologi Pilihan",
        focus: "Bagaimana moda transportasi dipilih untuk suatu pengiriman?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 33,
        title: "Kerangka Tata Kelola",
        focus: "Bagaimana gudang modern bekerja secara otomatis?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 34,
        title: "Infrastruktur & Tools",
        focus: "Bagaimana rute pengiriman dioptimalkan?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 35,
        title: "Strategi Implementasi",
        focus: "Bagaimana teknologi mengubah wajah logistik?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 36,
        title: "Metrik & Evaluasi",
        focus: "Bagaimana barang lintas batas negara diproses?",
        example: "",
        w5h1: "HOW",
      },
    ],
  },
  {
    id: 5,
    title: "Logistik",
    subtitle: "Perpindahan Value",
    tagline: '"Kenapa barang bisa sampai ke rumah Anda dalam sehari."',
    description:
      "Pernahkah kamu memesan barang dan esok harinya sudah sampai di depan pintu? Di bab ini, kita akan mengikuti perjalanan panjang sebuah barang dari pabrik hingga ke tangan konsumen, serta sistem kompleks di baliknya.",
    subChapters: [
      {
        id: 1,
        title: "Definisi",
        focus: "Apa itu komunikasi organisasi?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 2,
        title: "Objek",
        focus: "Apa itu pemasaran (marketing)?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 3,
        title: "Klasifikasi",
        focus: "Apa itu periklanan (iklan)?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 4,
        title: "Komponen",
        focus: "Apa itu penyiaran (siar)?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 5,
        title: "Struktur",
        focus: "Apa itu branding?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 6,
        title: "Karakteristik",
        focus: "Apa itu hubungan masyarakat (PR)?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 7,
        title: "Tujuan",
        focus: "Siapa pengirim dan penerima dalam proses komunikasi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 8,
        title: "Urgensi",
        focus: "Siapa target audiens suatu kampanye pemasaran?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 9,
        title: "Manfaat Makro",
        focus: "Siapa yang menyusun strategi PR perusahaan?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 10,
        title: "Manfaat Mikro",
        focus: "Siapa yang menyampaikan pesan lewat media penyiaran?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 11,
        title: "Resiko",
        focus: "Siapa yang bertanggung jawab menangani komunikasi krisis?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 12,
        title: "Kontribusi",
        focus: "Siapa yang rentan salah paham dalam komunikasi lintas budaya?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 13,
        title: "Pelaku Utama",
        focus: "Kapan pesan dianggap efektif tersampaikan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 14,
        title: "Pihak Pendukung",
        focus: "Kapan kampanye iklan sebaiknya diluncurkan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 15,
        title: "Penerima Manfaat",
        focus: "Kapan komunikasi krisis harus segera dilakukan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 16,
        title: "Regulator / Pengawas",
        focus: "Kapan storytelling lebih efektif dari data mentah?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 17,
        title: "Kompetensi SDM",
        focus: "Kapan konten dianggap berpotensi viral?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 18,
        title: "Pemimpin Puncak",
        focus: "Kapan komunikasi organisasi paling rentan mengalami distorsi?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 19,
        title: "Ruang Lingkup Internal",
        focus: "Dimana pesan pemasaran paling efektif disampaikan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 20,
        title: "Ruang Lingkup Eksternal",
        focus: "Dimana media penyiaran menjangkau audiens terluas?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 21,
        title: "Lokus Fisik",
        focus: "Dimana komunikasi digital paling banyak terjadi?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 22,
        title: "Lokus Digital",
        focus: "Dimana komunikasi lintas budaya paling sering menimbulkan masalah?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 23,
        title: "Jangkauan Ekosistem",
        focus: "Dimana branding membentuk persepsi paling kuat?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 24,
        title: "Hambatan Struktural",
        focus: "Dimana hubungan masyarakat berperan menjaga reputasi?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 25,
        title: "Fase Inisiasi",
        focus: "Mengapa pesan yang sama bisa dipahami berbeda oleh tiap orang?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 26,
        title: "Fase Pertumbuhan",
        focus: "Mengapa cerita lebih mudah diingat dari data mentah?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 27,
        title: "Fase Kematangan",
        focus: "Mengapa branding membuat satu produk terasa lebih premium?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 28,
        title: "Fase Krisis",
        focus: "Mengapa komunikasi krisis harus dilakukan dengan hati-hati?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 29,
        title: "Siklus Kritis",
        focus: "Mengapa distorsi pesan sering terjadi dalam organisasi berjenjang?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 30,
        title: "Horizon Waktu",
        focus: "Mengapa komunikasi lintas budaya rentan disalahpahami?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 31,
        title: "Mekanisme Dasar",
        focus: "Bagaimana elemen pengirim-pesan-penerima bekerja dalam komunikasi?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 32,
        title: "Metodologi Pilihan",
        focus: "Bagaimana media sosial mengubah cara pesan menyebar?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 33,
        title: "Kerangka Tata Kelola",
        focus: "Bagaimana iklan membujuk tanpa terasa memaksa?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 34,
        title: "Infrastruktur & Tools",
        focus: "Bagaimana PR menjaga citra perusahaan di mata publik?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 35,
        title: "Strategi Implementasi",
        focus: "Bagaimana negosiasi menyampaikan kepentingan agar diterima pihak lain?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 36,
        title: "Metrik & Evaluasi",
        focus: "Bagaimana pesan buruk disampaikan tanpa memperburuk keadaan?",
        example: "",
        w5h1: "HOW",
      },
    ],
  },

  {
    id: 6,
    title: "Bisnis",
    subtitle: "Pertukaran Value",
    tagline: '"Kenapa produk bagus bisa gagal, dan produk biasa bisa laris."',
    description:
      "Pernahkah kamu melihat bisnis kecil yang tiba-tiba ramai, lalu sebulan kemudian sepi dan terpaksa tutup? Atau heran kenapa produk yang biasa saja bisa laris manis, sementara yang inovatif malah gagal? Di bab ini, kita akan mempelajari dinamika bisnis—mulai dari bagaimana produk diciptakan, dijual, hingga cara bertahan di tengah persaingan pasar yang kejam.",
    subChapters: [
      {
        id: 1,
        title: "Definisi",
        focus: "Apa itu struktur organisasi?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 2,
        title: "Objek",
        focus: "Apa itu manajemen risiko?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 3,
        title: "Klasifikasi",
        focus: "Apa itu manajemen kinerja (KPI)?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 4,
        title: "Komponen",
        focus: "Apa itu manajemen mutu?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 5,
        title: "Struktur",
        focus: "Apa itu manajemen proyek?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 6,
        title: "Karakteristik",
        focus: "Apa itu manajemen perubahan?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 7,
        title: "Tujuan",
        focus: "Siapa yang berperan sebagai pemimpin dalam organisasi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 8,
        title: "Urgensi",
        focus: "Siapa yang bertanggung jawab atas SDM?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 9,
        title: "Manfaat Makro",
        focus: "Siapa yang mengelola proyek?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 10,
        title: "Manfaat Mikro",
        focus: "Siapa yang menilai kinerja karyawan?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 11,
        title: "Resiko",
        focus: "Siapa yang terlibat dalam pengambilan keputusan?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 12,
        title: "Kontribusi",
        focus: "Siapa yang menangani konflik dalam tim?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 13,
        title: "Pelaku Utama",
        focus: "Kapan organisasi perlu mengubah strukturnya?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 14,
        title: "Pihak Pendukung",
        focus: "Kapan proyek dianggap gagal?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 15,
        title: "Penerima Manfaat",
        focus: "Kapan keputusan harus diambil secara cepat?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 16,
        title: "Regulator / Pengawas",
        focus: "Kapan delegasi tugas diperlukan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 17,
        title: "Kompetensi SDM",
        focus: "Kapan evaluasi kinerja dilakukan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 18,
        title: "Pemimpin Puncak",
        focus: "Kapan risiko harus segera dimitigasi?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 19,
        title: "Ruang Lingkup Internal",
        focus: "Dimana letak masalah operasional biasa terjadi?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 20,
        title: "Ruang Lingkup Eksternal",
        focus: "Dimana konflik tim paling sering muncul?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 21,
        title: "Lokus Fisik",
        focus: "Dimana keputusan strategis biasanya dibuat?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 22,
        title: "Lokus Digital",
        focus: "Dimana manajemen waktu paling dibutuhkan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 23,
        title: "Jangkauan Ekosistem",
        focus: "Dimana inovasi dalam manajemen paling terasa dampaknya?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 24,
        title: "Hambatan Struktural",
        focus: "Dimana standar mutu diterapkan dalam organisasi?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 25,
        title: "Fase Inisiasi",
        focus: "Mengapa tim berisi orang pintar bisa tetap gagal?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 26,
        title: "Fase Pertumbuhan",
        focus: "Mengapa perubahan organisasi sering ditolak?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 27,
        title: "Fase Kematangan",
        focus: "Mengapa proyek sering molor dari jadwal?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 28,
        title: "Fase Krisis",
        focus: "Mengapa motivasi karyawan penting dijaga?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 29,
        title: "Siklus Kritis",
        focus: "Mengapa gaya kepemimpinan harus disesuaikan dengan situasi?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 30,
        title: "Horizon Waktu",
        focus: "Mengapa manajemen risiko mencegah kerugian besar?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 31,
        title: "Mekanisme Dasar",
        focus: "Bagaimana struktur organisasi menentukan alur kerja?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 32,
        title: "Metodologi Pilihan",
        focus: "Bagaimana pemimpin mengambil keputusan di masa krisis?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 33,
        title: "Kerangka Tata Kelola",
        focus: "Bagaimana kinerja diukur tanpa terjebak angka semata?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 34,
        title: "Infrastruktur & Tools",
        focus: "Bagaimana konflik dikelola agar tetap sehat?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 35,
        title: "Strategi Implementasi",
        focus: "Bagaimana delegasi dilakukan tanpa kehilangan kendali?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 36,
        title: "Metrik & Evaluasi",
        focus: "Bagaimana mutu dijaga tetap konsisten?",
        example: "",
        w5h1: "HOW",
      },
    ],
  },
  {
    id: 7,
    title: "Administrasi",
    subtitle: "Pembukuan Value",
    tagline: '"Pekerjaan paling membosankan yang sebenarnya menyelamatkan organisasi."',
    description:
      "Pernahkah kamu melihat akibat fatal dari dokumen yang hilang atau salah prosedur? Pekerjaan ini sering dianggap sepele, namun di bab ini kita akan membahas bagaimana proses administrasi yang rapi bisa menjadi penentu hidup matinya sebuah organisasi atau bisnis.",
    subChapters: [
      {
        id: 1,
        title: "Definisi",
        focus: "Apa itu dokumen legal?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 2,
        title: "Objek",
        focus: "Apa itu arsip?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 3,
        title: "Klasifikasi",
        focus: "Apa itu SOP (prosedur)?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 4,
        title: "Komponen",
        focus: "Apa itu pengadaan barang/jasa?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 5,
        title: "Struktur",
        focus: "Apa itu inventaris?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 6,
        title: "Karakteristik",
        focus: "Apa itu administrasi kepegawaian?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 7,
        title: "Tujuan",
        focus: "Siapa yang berwenang menandatangani dokumen?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 8,
        title: "Urgensi",
        focus: "Siapa yang mengelola arsip organisasi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 9,
        title: "Manfaat Makro",
        focus: "Siapa yang bertanggung jawab atas pengadaan?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 10,
        title: "Manfaat Mikro",
        focus: "Siapa yang mencatat persediaan barang?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 11,
        title: "Resiko",
        focus: "Siapa yang menyusun laporan administratif?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 12,
        title: "Kontribusi",
        focus: "Siapa yang mengakses data administratif karyawan?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 13,
        title: "Pelaku Utama",
        focus: "Kapan dokumen harus diarsipkan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 14,
        title: "Pihak Pendukung",
        focus: "Kapan SOP perlu diperbarui?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 15,
        title: "Penerima Manfaat",
        focus: "Kapan proses pengadaan dimulai?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 16,
        title: "Regulator / Pengawas",
        focus: "Kapan laporan administratif harus diserahkan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 17,
        title: "Kompetensi SDM",
        focus: "Kapan inventaris harus diperiksa ulang?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 18,
        title: "Pemimpin Puncak",
        focus: "Kapan data administratif dianggap kedaluwarsa?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 19,
        title: "Ruang Lingkup Internal",
        focus: "Dimana dokumen penting disimpan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 20,
        title: "Ruang Lingkup Eksternal",
        focus: "Dimana proses tender/pengadaan dilakukan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 21,
        title: "Lokus Fisik",
        focus: "Dimana layanan administrasi publik diakses?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 22,
        title: "Lokus Digital",
        focus: "Dimana data administratif rentan bocor?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 23,
        title: "Jangkauan Ekosistem",
        focus: "Dimana formulir standar digunakan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 24,
        title: "Hambatan Struktural",
        focus: "Dimana alur persetujuan dokumen melewati banyak pihak?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 25,
        title: "Fase Inisiasi",
        focus: "Mengapa selembar dokumen bisa jadi bukti hukum?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 26,
        title: "Fase Pertumbuhan",
        focus: "Mengapa arsip lama tetap penting disimpan?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 27,
        title: "Fase Kematangan",
        focus: "Mengapa SOP terasa membosankan tapi menyelamatkan?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 28,
        title: "Fase Krisis",
        focus: "Mengapa harga proyek pengadaan pemerintah bisa mahal?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 29,
        title: "Siklus Kritis",
        focus: "Mengapa keamanan data administratif harus dijaga?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 30,
        title: "Horizon Waktu",
        focus: "Mengapa administrasi kepegawaian sering dianggap remeh?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 31,
        title: "Mekanisme Dasar",
        focus: "Bagaimana dokumen dikelola agar tidak hilang?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 32,
        title: "Metodologi Pilihan",
        focus: "Bagaimana proses pengadaan barang/jasa berjalan?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 33,
        title: "Kerangka Tata Kelola",
        focus: 'Bagaimana persediaan dicatat agar tidak "hilang" tanpa jejak?',
        example: "",
        w5h1: "HOW",
      },
      {
        id: 34,
        title: "Infrastruktur & Tools",
        focus: "Bagaimana layanan administrasi publik melayani warga?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 35,
        title: "Strategi Implementasi",
        focus: "Bagaimana digitalisasi mengubah cara kerja administrasi?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 36,
        title: "Metrik & Evaluasi",
        focus: "Bagaimana tata kelola dokumen mengatur siapa berhak mengubah apa?",
        example: "",
        w5h1: "HOW",
      },
    ],
  },
  {
    id: 8,
    title: "Akuntansi",
    subtitle: "Pencatatan Value",
    tagline: '"Angka-angka yang menentukan hidup-matinya perusahaan."',
    description:
      "Pernahkah kamu mendengar cerita perusahaan besar yang tiba-tiba bangkrut karena salah kelola keuangan? Di bab ini, kita akan mempelajari angka-angka sebagai bahasa bisnis, mulai dari cara membaca laporan tanpa harus jadi akuntan hingga membedakan utang sehat dan berbahaya.",
    subChapters: [
      {
        id: 1,
        title: "Definisi",
        focus: "Apa itu laporan keuangan?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 2,
        title: "Objek",
        focus: "Apa itu akuntansi biaya?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 3,
        title: "Klasifikasi",
        focus: "Apa itu audit?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 4,
        title: "Komponen",
        focus: "Apa itu anggaran (budgeting)?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 5,
        title: "Struktur",
        focus: "Apa itu aset dan liabilitas?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 6,
        title: "Karakteristik",
        focus: "Apa itu titik impas (BEP)?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 7,
        title: "Tujuan",
        focus: "Siapa yang menyusun laporan keuangan?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 8,
        title: "Urgensi",
        focus: "Siapa yang melakukan audit?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 9,
        title: "Manfaat Makro",
        focus: "Siapa yang mengelola anggaran perusahaan?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 10,
        title: "Manfaat Mikro",
        focus: "Siapa yang bertanggung jawab atas kepatuhan pajak?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 11,
        title: "Resiko",
        focus: "Siapa pengguna laporan keuangan?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 12,
        title: "Kontribusi",
        focus: "Siapa yang mengungkap kecurangan lewat akuntansi forensik?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 13,
        title: "Pelaku Utama",
        focus: "Kapan laporan keuangan harus dipublikasikan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 14,
        title: "Pihak Pendukung",
        focus: "Kapan audit dilakukan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 15,
        title: "Penerima Manfaat",
        focus: "Kapan anggaran biasanya disusun ulang?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 16,
        title: "Regulator / Pengawas",
        focus: "Kapan perusahaan wajib membayar pajak?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 17,
        title: "Kompetensi SDM",
        focus: "Kapan aset dianggap menyusut nilainya?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 18,
        title: "Pemimpin Puncak",
        focus: "Kapan bisnis mencapai titik impas?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 19,
        title: "Ruang Lingkup Internal",
        focus: "Dimana standar akuntansi berbeda antarnegara?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 20,
        title: "Ruang Lingkup Eksternal",
        focus: "Dimana laporan keuangan konsolidasi dibutuhkan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 21,
        title: "Lokus Fisik",
        focus: "Dimana kecurangan keuangan paling sering ditemukan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 22,
        title: "Lokus Digital",
        focus: "Dimana insentif pajak biasa diberikan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 23,
        title: "Jangkauan Ekosistem",
        focus: "Dimana akuntansi syariah diterapkan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 24,
        title: "Hambatan Struktural",
        focus: "Dimana batas utang produktif dan konsumtif ditentukan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 25,
        title: "Fase Inisiasi",
        focus: "Mengapa harga jual bukan sekadar untung-untungan?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 26,
        title: "Fase Pertumbuhan",
        focus: "Mengapa perlu pihak ketiga memeriksa laporan keuangan?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 27,
        title: "Fase Kematangan",
        focus: "Mengapa anggaran sering meleset dari rencana?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 28,
        title: "Fase Krisis",
        focus: "Mengapa nilai aset menyusut seiring waktu?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 29,
        title: "Siklus Kritis",
        focus: "Mengapa utang bisa sehat atau berbahaya?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 30,
        title: "Horizon Waktu",
        focus: "Mengapa pajak bukan sekadar kewajiban semata?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 31,
        title: "Mekanisme Dasar",
        focus: "Bagaimana membaca laporan keuangan tanpa jadi akuntan?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 32,
        title: "Metodologi Pilihan",
        focus: "Bagaimana biaya produksi dihitung?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 33,
        title: "Kerangka Tata Kelola",
        focus: "Bagaimana rasio keuangan mencerminkan kesehatan perusahaan?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 34,
        title: "Infrastruktur & Tools",
        focus: "Bagaimana software mengubah cara pembukuan dilakukan?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 35,
        title: "Strategi Implementasi",
        focus: "Bagaimana laporan keuangan induk-anak perusahaan disatukan?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 36,
        title: "Metrik & Evaluasi",
        focus: "Bagaimana titik impas dihitung dalam usaha kecil?",
        example: "",
        w5h1: "HOW",
      },
    ],
  },
  {
    id: 9,
    title: "Asuransi",
    subtitle: "Pelindung Value",
    tagline: '"Membayar untuk sesuatu yang (semoga) tidak pernah terjadi."',
    description:
      "Pernahkah kamu mendengar cerita klaim asuransi yang menyelamatkan hidup atau keuangan seseorang dari kehancuran total? Di bab ini, kita akan membahas logika di balik membayar uang untuk sesuatu yang kita harap tidak akan pernah kita gunakan.",
    subChapters: [
      {
        id: 1,
        title: "Definisi",
        focus: "Apa itu polis asuransi?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 2,
        title: "Objek",
        focus: "Apa itu premi?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 3,
        title: "Klasifikasi",
        focus: "Apa itu klaim?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 4,
        title: "Komponen",
        focus: "Apa itu underwriting?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 5,
        title: "Struktur",
        focus: "Apa itu reasuransi?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 6,
        title: "Karakteristik",
        focus: "Apa itu insurtech?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 7,
        title: "Tujuan",
        focus: "Siapa yang menetapkan besaran premi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 8,
        title: "Urgensi",
        focus: "Siapa yang memproses klaim asuransi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 9,
        title: "Manfaat Makro",
        focus: "Siapa yang diawasi oleh regulator asuransi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 10,
        title: "Manfaat Mikro",
        focus: "Siapa yang membutuhkan asuransi mikro?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 11,
        title: "Resiko",
        focus: "Siapa penerima manfaat dari asuransi jiwa?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 12,
        title: "Kontribusi",
        focus: "Siapa yang menanggung risiko dalam reasuransi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 13,
        title: "Pelaku Utama",
        focus: "Kapan klaim asuransi biasanya ditolak?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 14,
        title: "Pihak Pendukung",
        focus: "Kapan premi asuransi berubah?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 15,
        title: "Penerima Manfaat",
        focus: "Kapan asuransi jiwa paling dibutuhkan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 16,
        title: "Regulator / Pengawas",
        focus: "Kapan reasuransi diperlukan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 17,
        title: "Kompetensi SDM",
        focus: "Kapan asuransi kesehatan mulai berlaku?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 18,
        title: "Pemimpin Puncak",
        focus: "Kapan asuransi kargo melindungi barang dalam perjalanan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 19,
        title: "Ruang Lingkup Internal",
        focus: "Dimana industri asuransi diawasi?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 20,
        title: "Ruang Lingkup Eksternal",
        focus: "Dimana asuransi properti komersial paling dibutuhkan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 21,
        title: "Lokus Fisik",
        focus: "Dimana asuransi mikro paling relevan diterapkan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 22,
        title: "Lokus Digital",
        focus: "Dimana klaim asuransi bisa diajukan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 23,
        title: "Jangkauan Ekosistem",
        focus: "Dimana insurtech mengubah cara masyarakat membeli asuransi?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 24,
        title: "Hambatan Struktural",
        focus: "Dimana risiko yang tidak terlihat justru paling berbahaya?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 25,
        title: "Fase Inisiasi",
        focus: "Mengapa manusia buruk menilai risiko sendiri?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 26,
        title: "Fase Pertumbuhan",
        focus: "Mengapa premi tiap orang bisa berbeda?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 27,
        title: "Fase Kematangan",
        focus: "Mengapa perlu reasuransi dari asuransi?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 28,
        title: "Fase Krisis",
        focus: "Mengapa asuransi jiwa bukan soal kematian tapi yang ditinggalkan?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 29,
        title: "Siklus Kritis",
        focus: "Mengapa biaya sakit bisa menghancurkan keuangan keluarga?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 30,
        title: "Horizon Waktu",
        focus: "Mengapa banyak orang salah paham soal asuransi?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 31,
        title: "Mekanisme Dasar",
        focus: "Bagaimana premi asuransi dihitung?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 32,
        title: "Metodologi Pilihan",
        focus: "Bagaimana proses klaim diselesaikan?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 33,
        title: "Kerangka Tata Kelola",
        focus: "Bagaimana underwriting menentukan kelayakan seseorang?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 34,
        title: "Infrastruktur & Tools",
        focus: "Bagaimana teknologi mengubah cara klaim diajukan?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 35,
        title: "Strategi Implementasi",
        focus: "Bagaimana membaca polis tanpa terjebak istilah rumit?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 36,
        title: "Metrik & Evaluasi",
        focus: "Bagaimana asuransi melindungi barang dalam perjalanan?",
        example: "",
        w5h1: "HOW",
      },
    ],
  },
  {
    id: 10,
    title: "Investasi",
    subtitle: "Penambah Value",
    tagline: '"Membuat uang bekerja, bukan cuma disimpan."',
    description:
      "Pernahkah kamu mendengar cerita tentang dua orang: satu menabung biasa saja, dan satu lagi berinvestasi? Di bab ini, kita akan membahas berbagai instrumen untuk membuat uangmu bekerja untukmu, bukan sebaliknya.",
    subChapters: [
      {
        id: 1,
        title: "Definisi",
        focus: "Apa itu saham?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 2,
        title: "Objek",
        focus: "Apa itu obligasi?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 3,
        title: "Klasifikasi",
        focus: "Apa itu reksa dana?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 4,
        title: "Komponen",
        focus: "Apa itu valuasi?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 5,
        title: "Struktur",
        focus: "Apa itu portofolio?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 6,
        title: "Karakteristik",
        focus: "Apa itu bunga berbunga (compound interest)?",
        example: "",
        w5h1: "WHAT",
      },
      {
        id: 7,
        title: "Tujuan",
        focus: "Siapa yang menerbitkan obligasi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 8,
        title: "Urgensi",
        focus: "Siapa yang mengelola reksa dana?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 9,
        title: "Manfaat Makro",
        focus: "Siapa yang rentan tertipu skema investasi bodong?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 10,
        title: "Manfaat Mikro",
        focus: "Siapa yang membutuhkan dana pensiun?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 11,
        title: "Resiko",
        focus: "Siapa yang menganalisis kelayakan investasi?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 12,
        title: "Kontribusi",
        focus: "Siapa yang cocok berinvestasi jangka panjang vs pendek?",
        example: "",
        w5h1: "WHY",
      },
      {
        id: 13,
        title: "Pelaku Utama",
        focus: "Kapan waktu tepat mulai berinvestasi?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 14,
        title: "Pihak Pendukung",
        focus: "Kapan saham dianggap murah atau mahal?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 15,
        title: "Penerima Manfaat",
        focus: "Kapan investasi jangka pendek lebih cocok dari jangka panjang?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 16,
        title: "Regulator / Pengawas",
        focus: "Kapan risiko investasi tinggi sepadan dengan imbal hasilnya?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 17,
        title: "Kompetensi SDM",
        focus: "Kapan dana pensiun mulai harus dipersiapkan?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 18,
        title: "Pemimpin Puncak",
        focus: "Kapan tanda-tanda penipuan investasi mulai terlihat?",
        example: "",
        w5h1: "WHO",
      },
      {
        id: 19,
        title: "Ruang Lingkup Internal",
        focus: "Dimana investasi properti paling menguntungkan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 20,
        title: "Ruang Lingkup Eksternal",
        focus: "Dimana investasi syariah bisa diakses?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 21,
        title: "Lokus Fisik",
        focus: "Dimana risiko investasi kripto paling terasa?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 22,
        title: "Lokus Digital",
        focus: "Dimana literasi keuangan paling dibutuhkan?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 23,
        title: "Jangkauan Ekosistem",
        focus: "Dimana emas berperan sebagai aset lindung nilai?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 24,
        title: "Hambatan Struktural",
        focus: "Dimana startup mendapatkan valuasi tinggi?",
        example: "",
        w5h1: "WHERE",
      },
      {
        id: 25,
        title: "Fase Inisiasi",
        focus: "Mengapa menabung saja tidak cukup dibanding berinvestasi?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 26,
        title: "Fase Pertumbuhan",
        focus: "Mengapa harga wajar suatu aset sulit ditentukan?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 27,
        title: "Fase Kematangan",
        focus: 'Mengapa "jangan taruh telur di satu keranjang" itu benar?',
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 28,
        title: "Fase Krisis",
        focus: "Mengapa imbal hasil tinggi selalu berarti risiko tinggi?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 29,
        title: "Siklus Kritis",
        focus: "Mengapa mulai investasi lebih awal sangat berpengaruh?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 30,
        title: "Horizon Waktu",
        focus: "Mengapa literasi keuangan harus dikuasai sebelum berinvestasi?",
        example: "",
        w5h1: "WHEN",
      },
      {
        id: 31,
        title: "Mekanisme Dasar",
        focus: "Bagaimana seseorang memiliki sebagian kecil perusahaan lewat saham?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 32,
        title: "Metodologi Pilihan",
        focus: "Bagaimana reksa dana mendiversifikasi investasi secara otomatis?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 33,
        title: "Kerangka Tata Kelola",
        focus: "Bagaimana analisis fundamental dan teknikal membaca peluang?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 34,
        title: "Infrastruktur & Tools",
        focus: "Bagaimana portofolio investasi disusun secara seimbang?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 35,
        title: "Strategi Implementasi",
        focus: "Bagaimana skema ponzi bekerja menipu investor?",
        example: "",
        w5h1: "HOW",
      },
      {
        id: 36,
        title: "Metrik & Evaluasi",
        focus: "Bagaimana bunga berbunga membuat uang tumbuh signifikan?",
        example: "",
        w5h1: "HOW",
      },
    ],
  },
];
