import {
  LayoutDashboard,
  Users,
  FolderKanban,
  CheckSquare,
  CheckCircle2,
  Sparkles,
  NotebookText,
  CalendarDays,
  Compass,
  Gauge,
  MessagesSquare,
  CalendarClock,
  FolderOpen,
  Activity,
  LineChart,
  AlertTriangle,
  FileText,
  Shield,
  Calculator,
  HeartHandshake,
  Navigation,
  Building,
  TrendingUp,
  Package,
  Grid2X2,
  MoreHorizontal,
  Star,
  User,
  Settings,
  Wallet,
  CreditCard,
  ChevronDown,
  ChevronRight,
  Droplet,
  Timer,
  Briefcase,
  Target,
  BookOpen,
  Bookmark,
  Lightbulb,
  Eye,
  Key,
  Dumbbell,
  Utensils,
  Music,
  CloudSun,
  Book,
  Plane,
  ShoppingCart,
  Heart,
  HeartPulse,
  Archive,
  GraduationCap,
  Layers,
  FileCheck,
  Globe,
  Film,
  Gamepad2,
  Podcast,
  Ticket,
  PenTool,
  Camera,
  Type,
  Code,
  DollarSign,
  ShieldCheck,
  RefreshCw,
  Building2,
  Sprout,
  Search,
  Bell,
  Coins,
  MessageCircle,
  Truck,
  Store,
  Home,
  ScrollText,
  Binary,
  Info,
  Pocket,
  Vault,
  Luggage,
  ShoppingBag,
  type LucideIcon,
} from "lucide-react";

export type NavItem = {
  to: string;
  label: string;
  icon: LucideIcon;
};

export type NavGroup = {
  title: string;
  items: NavItem[];
};

export const navKonsultan: NavGroup[] = [
  {
    title: "Tahapan",
    items: [
      { to: "/100-framework", label: "100 Framework", icon: Grid2X2 },
      { to: "/100-komoditas", label: "100 Komoditas", icon: Package },
    ],
  },
  {
    title: "Proyek",
    items: [
      { to: "/proyek", label: "Proyek & Tugas", icon: FolderKanban },
      { to: "/proyek-personal", label: "Personal Projects", icon: Briefcase },
      { to: "/countdown", label: "Countdown", icon: Timer },
      { to: "/katalog-produk", label: "Katalog Produk", icon: Package },
      { to: "/reports", label: "Laporan Khusus", icon: NotebookText },
    ],
  },
  {
    title: "Overview",
    items: [
      { to: "/insider", label: "Insider", icon: Eye },
      { to: "/insight", label: "Insight", icon: Lightbulb },
      { to: "/outward", label: "Outward", icon: Compass },
      { to: "/outlook", label: "Outlook", icon: TrendingUp },
      { to: "/bookmarks", label: "Bookmarks", icon: Bookmark },
      { to: "/events", label: "Events", icon: Ticket },
      { to: "/weather", label: "Weather", icon: CloudSun },
    ],
  },
  {
    title: "Productivity",
    items: [
      { to: "/kalender", label: "Kalender & Timeline", icon: CalendarDays },
      { to: "/task-manager", label: "Task Manager", icon: CheckSquare },
      { to: "/pomodoro", label: "Pomodoro Timer", icon: Timer },
      { to: "/eisenhower", label: "Eisenhower Matrix", icon: Grid2X2 },
      { to: "/incoterms", label: "Panduan Incoterms", icon: Navigation },
    ],
  },
  {
    title: "Portal Klien",
    items: [
      { to: "/portal", label: "Ringkasan", icon: LayoutDashboard },
      { to: "/portal/progres", label: "Progres", icon: Gauge },
      { to: "/portal/pesan", label: "Pesan", icon: MessagesSquare },
      { to: "/portal/jadwal", label: "Jadwal", icon: CalendarClock },
      { to: "/portal/dokumen", label: "Dokumen", icon: FolderOpen },
    ],
  },
  {
    title: "Asset",
    items: [
      { to: "/asset", label: "Kuadran Aset", icon: Briefcase },
      { to: "/liquid-reserves", label: "Liquid Reserves", icon: Coins },
      { to: "/physical-commodities", label: "Physical Commodities", icon: Package },
      { to: "/real-estate", label: "Real Estate", icon: Home },
      { to: "/paper-securities", label: "Paper Securities", icon: ScrollText },
      { to: "/digital-assets", label: "Digital Assets", icon: Binary },
      { to: "/intellectual-property", label: "Intellectual Property", icon: Lightbulb },
    ],
  },
  {
    title: "Liability",
    items: [{ to: "/liability", label: "Kuadran Liabilitas", icon: CreditCard }],
  },
  {
    title: "Earning",
    items: [{ to: "/earning", label: "Kuadran Pendapatan", icon: DollarSign }],
  },
  {
    title: "Expense",
    items: [{ to: "/expense", label: "Kuadran Pengeluaran", icon: ShoppingCart }],
  },
  {
    title: "5 Tahap Keuangan",
    items: [
      { to: "/surety", label: "Tahap 1: Surety", icon: ShieldCheck },
      { to: "/flow", label: "Tahap 2: Flow", icon: RefreshCw },
      { to: "/build", label: "Tahap 3: Build", icon: Building2 },
      { to: "/grow", label: "Tahap 4: Grow", icon: Sprout },
      { to: "/legacy", label: "Tahap 5: Legacy", icon: BookOpen },
    ],
  },
  {
    title: "Value Treated",
    items: [
      { to: "/kurasi/ekonomi", label: "Ekonomi", icon: Coins },
      { to: "/kurasi/statistik", label: "Statistik", icon: LineChart },
      { to: "/kurasi/manajemen", label: "Manajemen", icon: Briefcase },
      { to: "/kurasi/komunikasi", label: "Komunikasi", icon: MessageCircle },
      { to: "/kurasi/logistik", label: "Logistik", icon: Truck },
      { to: "/kurasi/bisnis", label: "Bisnis", icon: Store },
      { to: "/kurasi/administrasi", label: "Administrasi", icon: FileText },
      { to: "/kurasi/akuntansi", label: "Akuntansi", icon: Calculator },
      { to: "/kurasi/asuransi", label: "Asuransi", icon: Shield },
      { to: "/kurasi/investasi", label: "Investasi", icon: TrendingUp },
      { to: "/swot", label: "SWOT Analysis", icon: Target },
    ],
  },
  {
    title: "Keuangan & Investasi",
    items: [
      { to: "/finances", label: "Finances", icon: DollarSign },
      { to: "/budget", label: "Budget", icon: Wallet },
      { to: "/kredit", label: "Kredit & Utang", icon: CreditCard },
      { to: "/subscriptions", label: "Subscriptions", icon: CreditCard },
      { to: "/pajak", label: "Kalkulator Pajak", icon: Calculator },
      { to: "/investasi", label: "Kalkulator Investasi", icon: TrendingUp },
      { to: "/valuasi", label: "Valuasi MAPPI", icon: Building },
      { to: "/financial-health", label: "Kesehatan Finansial", icon: HeartPulse },
    ],
  },
  {
    title: "Syariah & Muamalah",
    items: [
      { to: "/syariah", label: "Pasar Muamalah", icon: HeartHandshake },
      { to: "/syariah/indeks", label: "Indeks Sharia", icon: LineChart },
      { to: "/syariah/terlarang", label: "Transaksi Terlarang", icon: AlertTriangle },
      { to: "/syariah/akad", label: "Akad Syariah", icon: FileText },
      { to: "/syariah/asuransi", label: "Asuransi Syariah", icon: Shield },
      { to: "/zakat", label: "Kalkulator Zakat", icon: Calculator },
    ],
  },
  {
    title: "Education",
    items: [
      { to: "/courses", label: "Courses", icon: GraduationCap },
      { to: "/flashcards", label: "Flashcards", icon: Layers },
      { to: "/exams", label: "Exams", icon: FileCheck },
      { to: "/languages", label: "Languages", icon: Globe },
      { to: "/reading", label: "Reading List", icon: Book },
    ],
  },
  {
    title: "Wellbeing",
    items: [
      { to: "/health", label: "Health", icon: Heart },
      { to: "/workouts", label: "Workouts", icon: Dumbbell },
      { to: "/water", label: "Water Tracker", icon: Droplet },
    ],
  },
  {
    title: "Memos",
    items: [
      { to: "/notes", label: "Notes & Docs", icon: FileText },
      { to: "/catatan", label: "Catatan", icon: NotebookText },
      { to: "/ideas", label: "Ideas", icon: Lightbulb },
      { to: "/journal", label: "Journal", icon: BookOpen },
    ],
  },
  {
    title: "Personal",
    items: [
      { to: "/wallet", label: "Wallet", icon: Wallet },
      { to: "/pocket", label: "Pocket", icon: Pocket },
      { to: "/pouch", label: "Pouch", icon: ShoppingBag },
      { to: "/vault", label: "Vault", icon: Vault },
      { to: "/trunk", label: "Trunk", icon: Luggage },
      { to: "/contacts", label: "Kontak", icon: Users },
      { to: "/goals", label: "Goals", icon: Target },
      { to: "/habits", label: "Habits", icon: Activity },
      { to: "/passwords", label: "Passwords", icon: Key },
      { to: "/inventory", label: "Inventory", icon: Archive },
    ],
  },
  {
    title: "Lifestyle",
    items: [
      { to: "/recipes", label: "Recipes", icon: Utensils },
      { to: "/shopping", label: "Shopping List", icon: ShoppingCart },
      { to: "/trips", label: "Trips", icon: Plane },
    ],
  },
  {
    title: "Entertainment",
    items: [
      { to: "/movies", label: "Movies", icon: Film },
      { to: "/games", label: "Games", icon: Gamepad2 },
      { to: "/podcasts", label: "Podcasts", icon: Podcast },
      { to: "/music", label: "Music", icon: Music },
    ],
  },
  {
    title: "Creativity",
    items: [
      { to: "/design", label: "Design", icon: PenTool },
      { to: "/photography", label: "Photography", icon: Camera },
      { to: "/writing", label: "Writing", icon: Type },
      { to: "/code", label: "Code", icon: Code },
    ],
  },
  {
    title: "Lain-lain",
    items: [
      { to: "/kalkulator", label: "Kalkulator Umum", icon: Calculator },
    ],
  },
];
