/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R100FrameworkRouteImport } from './routes/100-framework'
import { Route as R100KomoditasRouteImport } from './routes/100-komoditas'
import { Route as AssetRouteImport } from './routes/asset'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as BuildRouteImport } from './routes/build'
import { Route as CatatanRouteImport } from './routes/catatan'
import { Route as CodeRouteImport } from './routes/code'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CountdownRouteImport } from './routes/countdown'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as DigitalAssetsRouteImport } from './routes/digital-assets'
import { Route as EarningRouteImport } from './routes/earning'
import { Route as EisenhowerRouteImport } from './routes/eisenhower'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as ExpenseRouteImport } from './routes/expense'
import { Route as FavoritRouteImport } from './routes/favorit'
import { Route as FinancesRouteImport } from './routes/finances'
import { Route as FinancialHealthRouteImport } from './routes/financial-health'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as GamesRouteImport } from './routes/games'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as GrowRouteImport } from './routes/grow'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as ImprovementRouteImport } from './routes/improvement'
import { Route as IncotermsRouteImport } from './routes/incoterms'
import { Route as InsiderRouteImport } from './routes/insider'
import { Route as InsightRouteImport } from './routes/insight'
import { Route as IntellectualPropertyRouteImport } from './routes/intellectual-property'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvestasiRouteImport } from './routes/investasi'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as KatalogProdukRouteImport } from './routes/katalog-produk'
import { Route as KlienRouteImport } from './routes/klien'
import { Route as KreditRouteImport } from './routes/kredit'
import { Route as LainnyaRouteImport } from './routes/lainnya'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as LiabilityRouteImport } from './routes/liability'
import { Route as LiquidReservesRouteImport } from './routes/liquid-reserves'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MusicRouteImport } from './routes/music'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as OutlookRouteImport } from './routes/outlook'
import { Route as OutwardRouteImport } from './routes/outward'
import { Route as PajakRouteImport } from './routes/pajak'
import { Route as PaperSecuritiesRouteImport } from './routes/paper-securities'
import { Route as PasswordsRouteImport } from './routes/passwords'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as PhysicalCommoditiesRouteImport } from './routes/physical-commodities'
import { Route as PocketRouteImport } from './routes/pocket'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as PomodoroRouteImport } from './routes/pomodoro'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PouchRouteImport } from './routes/pouch'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ProyekRouteImport } from './routes/proyek'
import { Route as ProyekPersonalRouteImport } from './routes/proyek-personal'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as RelianceRouteImport } from './routes/reliance'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SufficentRouteImport } from './routes/sufficent'
import { Route as SuretyRouteImport } from './routes/surety'
import { Route as SwotRouteImport } from './routes/swot'
import { Route as TaskManagerRouteImport } from './routes/task-manager'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as TrunkRouteImport } from './routes/trunk'
import { Route as TugasRouteImport } from './routes/tugas'
import { Route as ValuasiRouteImport } from './routes/valuasi'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WaterRouteImport } from './routes/water'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as ZakatRouteImport } from './routes/zakat'
import { Route as KlienClientIdRouteImport } from './routes/klien.$clientId'
import { Route as KurasiSlugRouteImport } from './routes/kurasi.$slug'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalDokumenRouteImport } from './routes/portal.dokumen'
import { Route as PortalJadwalRouteImport } from './routes/portal.jadwal'
import { Route as PortalPesanRouteImport } from './routes/portal.pesan'
import { Route as PortalProgresRouteImport } from './routes/portal.progres'
import { Route as SyariahIndexRouteImport } from './routes/syariah.index'
import { Route as SyariahAkadRouteImport } from './routes/syariah.akad'
import { Route as SyariahAsuransiRouteImport } from './routes/syariah.asuransi'
import { Route as SyariahIndeksRouteImport } from './routes/syariah.indeks'
import { Route as SyariahTerlarangRouteImport } from './routes/syariah.terlarang'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R100FrameworkRoute = R100FrameworkRouteImport.update({
  id: '/100-framework',
  path: '/100-framework',
  getParentRoute: () => rootRouteImport,
} as any)
const R100KomoditasRoute = R100KomoditasRouteImport.update({
  id: '/100-komoditas',
  path: '/100-komoditas',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetRoute = AssetRouteImport.update({
  id: '/asset',
  path: '/asset',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const CatatanRoute = CatatanRouteImport.update({
  id: '/catatan',
  path: '/catatan',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CountdownRoute = CountdownRouteImport.update({
  id: '/countdown',
  path: '/countdown',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalAssetsRoute = DigitalAssetsRouteImport.update({
  id: '/digital-assets',
  path: '/digital-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningRoute = EarningRouteImport.update({
  id: '/earning',
  path: '/earning',
  getParentRoute: () => rootRouteImport,
} as any)
const EisenhowerRoute = EisenhowerRouteImport.update({
  id: '/eisenhower',
  path: '/eisenhower',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseRoute = ExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritRoute = FavoritRouteImport.update({
  id: '/favorit',
  path: '/favorit',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesRoute = FinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialHealthRoute = FinancialHealthRouteImport.update({
  id: '/financial-health',
  path: '/financial-health',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowRoute = GrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprovementRoute = ImprovementRouteImport.update({
  id: '/improvement',
  path: '/improvement',
  getParentRoute: () => rootRouteImport,
} as any)
const IncotermsRoute = IncotermsRouteImport.update({
  id: '/incoterms',
  path: '/incoterms',
  getParentRoute: () => rootRouteImport,
} as any)
const InsiderRoute = InsiderRouteImport.update({
  id: '/insider',
  path: '/insider',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightRoute = InsightRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => rootRouteImport,
} as any)
const IntellectualPropertyRoute = IntellectualPropertyRouteImport.update({
  id: '/intellectual-property',
  path: '/intellectual-property',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestasiRoute = InvestasiRouteImport.update({
  id: '/investasi',
  path: '/investasi',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogProdukRoute = KatalogProdukRouteImport.update({
  id: '/katalog-produk',
  path: '/katalog-produk',
  getParentRoute: () => rootRouteImport,
} as any)
const KlienRoute = KlienRouteImport.update({
  id: '/klien',
  path: '/klien',
  getParentRoute: () => rootRouteImport,
} as any)
const KreditRoute = KreditRouteImport.update({
  id: '/kredit',
  path: '/kredit',
  getParentRoute: () => rootRouteImport,
} as any)
const LainnyaRoute = LainnyaRouteImport.update({
  id: '/lainnya',
  path: '/lainnya',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LiabilityRoute = LiabilityRouteImport.update({
  id: '/liability',
  path: '/liability',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidReservesRoute = LiquidReservesRouteImport.update({
  id: '/liquid-reserves',
  path: '/liquid-reserves',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const OutlookRoute = OutlookRouteImport.update({
  id: '/outlook',
  path: '/outlook',
  getParentRoute: () => rootRouteImport,
} as any)
const OutwardRoute = OutwardRouteImport.update({
  id: '/outward',
  path: '/outward',
  getParentRoute: () => rootRouteImport,
} as any)
const PajakRoute = PajakRouteImport.update({
  id: '/pajak',
  path: '/pajak',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperSecuritiesRoute = PaperSecuritiesRouteImport.update({
  id: '/paper-securities',
  path: '/paper-securities',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordsRoute = PasswordsRouteImport.update({
  id: '/passwords',
  path: '/passwords',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalCommoditiesRoute = PhysicalCommoditiesRouteImport.update({
  id: '/physical-commodities',
  path: '/physical-commodities',
  getParentRoute: () => rootRouteImport,
} as any)
const PocketRoute = PocketRouteImport.update({
  id: '/pocket',
  path: '/pocket',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const PomodoroRoute = PomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PouchRoute = PouchRouteImport.update({
  id: '/pouch',
  path: '/pouch',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyekRoute = ProyekRouteImport.update({
  id: '/proyek',
  path: '/proyek',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyekPersonalRoute = ProyekPersonalRouteImport.update({
  id: '/proyek-personal',
  path: '/proyek-personal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelianceRoute = RelianceRouteImport.update({
  id: '/reliance',
  path: '/reliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SufficentRoute = SufficentRouteImport.update({
  id: '/sufficent',
  path: '/sufficent',
  getParentRoute: () => rootRouteImport,
} as any)
const SuretyRoute = SuretyRouteImport.update({
  id: '/surety',
  path: '/surety',
  getParentRoute: () => rootRouteImport,
} as any)
const SwotRoute = SwotRouteImport.update({
  id: '/swot',
  path: '/swot',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskManagerRoute = TaskManagerRouteImport.update({
  id: '/task-manager',
  path: '/task-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const TrunkRoute = TrunkRouteImport.update({
  id: '/trunk',
  path: '/trunk',
  getParentRoute: () => rootRouteImport,
} as any)
const TugasRoute = TugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => rootRouteImport,
} as any)
const ValuasiRoute = ValuasiRouteImport.update({
  id: '/valuasi',
  path: '/valuasi',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterRoute = WaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ZakatRoute = ZakatRouteImport.update({
  id: '/zakat',
  path: '/zakat',
  getParentRoute: () => rootRouteImport,
} as any)
const KlienClientIdRoute = KlienClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => KlienRoute,
} as any)
const KurasiSlugRoute = KurasiSlugRouteImport.update({
  id: '/kurasi/$slug',
  path: '/kurasi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDokumenRoute = PortalDokumenRouteImport.update({
  id: '/dokumen',
  path: '/dokumen',
  getParentRoute: () => PortalRoute,
} as any)
const PortalJadwalRoute = PortalJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPesanRoute = PortalPesanRouteImport.update({
  id: '/pesan',
  path: '/pesan',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProgresRoute = PortalProgresRouteImport.update({
  id: '/progres',
  path: '/progres',
  getParentRoute: () => PortalRoute,
} as any)
const SyariahIndexRoute = SyariahIndexRouteImport.update({
  id: '/syariah/',
  path: '/syariah/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyariahAkadRoute = SyariahAkadRouteImport.update({
  id: '/syariah/akad',
  path: '/syariah/akad',
  getParentRoute: () => rootRouteImport,
} as any)
const SyariahAsuransiRoute = SyariahAsuransiRouteImport.update({
  id: '/syariah/asuransi',
  path: '/syariah/asuransi',
  getParentRoute: () => rootRouteImport,
} as any)
const SyariahIndeksRoute = SyariahIndeksRouteImport.update({
  id: '/syariah/indeks',
  path: '/syariah/indeks',
  getParentRoute: () => rootRouteImport,
} as any)
const SyariahTerlarangRoute = SyariahTerlarangRouteImport.update({
  id: '/syariah/terlarang',
  path: '/syariah/terlarang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/100-framework': typeof R100FrameworkRoute
  '/100-komoditas': typeof R100KomoditasRoute
  '/asset': typeof AssetRoute
  '/bookmarks': typeof BookmarksRoute
  '/budget': typeof BudgetRoute
  '/build': typeof BuildRoute
  '/catatan': typeof CatatanRoute
  '/code': typeof CodeRoute
  '/contacts': typeof ContactsRoute
  '/countdown': typeof CountdownRoute
  '/courses': typeof CoursesRoute
  '/design': typeof DesignRoute
  '/development': typeof DevelopmentRoute
  '/digital-assets': typeof DigitalAssetsRoute
  '/earning': typeof EarningRoute
  '/eisenhower': typeof EisenhowerRoute
  '/events': typeof EventsRoute
  '/exams': typeof ExamsRoute
  '/expense': typeof ExpenseRoute
  '/favorit': typeof FavoritRoute
  '/finances': typeof FinancesRoute
  '/financial-health': typeof FinancialHealthRoute
  '/flashcards': typeof FlashcardsRoute
  '/flow': typeof FlowRoute
  '/games': typeof GamesRoute
  '/goals': typeof GoalsRoute
  '/grow': typeof GrowRoute
  '/habits': typeof HabitsRoute
  '/health': typeof HealthRoute
  '/home': typeof HomeRoute
  '/ideas': typeof IdeasRoute
  '/improvement': typeof ImprovementRoute
  '/incoterms': typeof IncotermsRoute
  '/insider': typeof InsiderRoute
  '/insight': typeof InsightRoute
  '/intellectual-property': typeof IntellectualPropertyRoute
  '/inventory': typeof InventoryRoute
  '/investasi': typeof InvestasiRoute
  '/journal': typeof JournalRoute
  '/kalender': typeof KalenderRoute
  '/katalog-produk': typeof KatalogProdukRoute
  '/klien': typeof KlienRouteWithChildren
  '/kredit': typeof KreditRoute
  '/lainnya': typeof LainnyaRoute
  '/languages': typeof LanguagesRoute
  '/legacy': typeof LegacyRoute
  '/liability': typeof LiabilityRoute
  '/liquid-reserves': typeof LiquidReservesRoute
  '/movies': typeof MoviesRoute
  '/music': typeof MusicRoute
  '/notes': typeof NotesRoute
  '/outlook': typeof OutlookRoute
  '/outward': typeof OutwardRoute
  '/pajak': typeof PajakRoute
  '/paper-securities': typeof PaperSecuritiesRoute
  '/passwords': typeof PasswordsRoute
  '/photography': typeof PhotographyRoute
  '/physical-commodities': typeof PhysicalCommoditiesRoute
  '/pocket': typeof PocketRoute
  '/podcasts': typeof PodcastsRoute
  '/pomodoro': typeof PomodoroRoute
  '/portal': typeof PortalRouteWithChildren
  '/pouch': typeof PouchRoute
  '/profil': typeof ProfilRoute
  '/proyek': typeof ProyekRoute
  '/proyek-personal': typeof ProyekPersonalRoute
  '/reading': typeof ReadingRoute
  '/real-estate': typeof RealEstateRoute
  '/recipes': typeof RecipesRoute
  '/reliance': typeof RelianceRoute
  '/shopping': typeof ShoppingRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/sufficent': typeof SufficentRoute
  '/surety': typeof SuretyRoute
  '/swot': typeof SwotRoute
  '/task-manager': typeof TaskManagerRoute
  '/terminal': typeof TerminalRoute
  '/trips': typeof TripsRoute
  '/trunk': typeof TrunkRoute
  '/tugas': typeof TugasRoute
  '/valuasi': typeof ValuasiRoute
  '/vault': typeof VaultRoute
  '/wallet': typeof WalletRoute
  '/water': typeof WaterRoute
  '/weather': typeof WeatherRoute
  '/workouts': typeof WorkoutsRoute
  '/writing': typeof WritingRoute
  '/zakat': typeof ZakatRoute
  '/klien/$clientId': typeof KlienClientIdRoute
  '/kurasi/$slug': typeof KurasiSlugRoute
  '/portal/dokumen': typeof PortalDokumenRoute
  '/portal/jadwal': typeof PortalJadwalRoute
  '/portal/pesan': typeof PortalPesanRoute
  '/portal/progres': typeof PortalProgresRoute
  '/syariah/akad': typeof SyariahAkadRoute
  '/syariah/asuransi': typeof SyariahAsuransiRoute
  '/syariah/indeks': typeof SyariahIndeksRoute
  '/syariah/terlarang': typeof SyariahTerlarangRoute
  '/portal/': typeof PortalIndexRoute
  '/syariah/': typeof SyariahIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/100-framework': typeof R100FrameworkRoute
  '/100-komoditas': typeof R100KomoditasRoute
  '/asset': typeof AssetRoute
  '/bookmarks': typeof BookmarksRoute
  '/budget': typeof BudgetRoute
  '/build': typeof BuildRoute
  '/catatan': typeof CatatanRoute
  '/code': typeof CodeRoute
  '/contacts': typeof ContactsRoute
  '/countdown': typeof CountdownRoute
  '/courses': typeof CoursesRoute
  '/design': typeof DesignRoute
  '/development': typeof DevelopmentRoute
  '/digital-assets': typeof DigitalAssetsRoute
  '/earning': typeof EarningRoute
  '/eisenhower': typeof EisenhowerRoute
  '/events': typeof EventsRoute
  '/exams': typeof ExamsRoute
  '/expense': typeof ExpenseRoute
  '/favorit': typeof FavoritRoute
  '/finances': typeof FinancesRoute
  '/financial-health': typeof FinancialHealthRoute
  '/flashcards': typeof FlashcardsRoute
  '/flow': typeof FlowRoute
  '/games': typeof GamesRoute
  '/goals': typeof GoalsRoute
  '/grow': typeof GrowRoute
  '/habits': typeof HabitsRoute
  '/health': typeof HealthRoute
  '/home': typeof HomeRoute
  '/ideas': typeof IdeasRoute
  '/improvement': typeof ImprovementRoute
  '/incoterms': typeof IncotermsRoute
  '/insider': typeof InsiderRoute
  '/insight': typeof InsightRoute
  '/intellectual-property': typeof IntellectualPropertyRoute
  '/inventory': typeof InventoryRoute
  '/investasi': typeof InvestasiRoute
  '/journal': typeof JournalRoute
  '/kalender': typeof KalenderRoute
  '/katalog-produk': typeof KatalogProdukRoute
  '/klien': typeof KlienRouteWithChildren
  '/kredit': typeof KreditRoute
  '/lainnya': typeof LainnyaRoute
  '/languages': typeof LanguagesRoute
  '/legacy': typeof LegacyRoute
  '/liability': typeof LiabilityRoute
  '/liquid-reserves': typeof LiquidReservesRoute
  '/movies': typeof MoviesRoute
  '/music': typeof MusicRoute
  '/notes': typeof NotesRoute
  '/outlook': typeof OutlookRoute
  '/outward': typeof OutwardRoute
  '/pajak': typeof PajakRoute
  '/paper-securities': typeof PaperSecuritiesRoute
  '/passwords': typeof PasswordsRoute
  '/photography': typeof PhotographyRoute
  '/physical-commodities': typeof PhysicalCommoditiesRoute
  '/pocket': typeof PocketRoute
  '/podcasts': typeof PodcastsRoute
  '/pomodoro': typeof PomodoroRoute
  '/pouch': typeof PouchRoute
  '/profil': typeof ProfilRoute
  '/proyek': typeof ProyekRoute
  '/proyek-personal': typeof ProyekPersonalRoute
  '/reading': typeof ReadingRoute
  '/real-estate': typeof RealEstateRoute
  '/recipes': typeof RecipesRoute
  '/reliance': typeof RelianceRoute
  '/shopping': typeof ShoppingRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/sufficent': typeof SufficentRoute
  '/surety': typeof SuretyRoute
  '/swot': typeof SwotRoute
  '/task-manager': typeof TaskManagerRoute
  '/terminal': typeof TerminalRoute
  '/trips': typeof TripsRoute
  '/trunk': typeof TrunkRoute
  '/tugas': typeof TugasRoute
  '/valuasi': typeof ValuasiRoute
  '/vault': typeof VaultRoute
  '/wallet': typeof WalletRoute
  '/water': typeof WaterRoute
  '/weather': typeof WeatherRoute
  '/workouts': typeof WorkoutsRoute
  '/writing': typeof WritingRoute
  '/zakat': typeof ZakatRoute
  '/klien/$clientId': typeof KlienClientIdRoute
  '/kurasi/$slug': typeof KurasiSlugRoute
  '/portal/dokumen': typeof PortalDokumenRoute
  '/portal/jadwal': typeof PortalJadwalRoute
  '/portal/pesan': typeof PortalPesanRoute
  '/portal/progres': typeof PortalProgresRoute
  '/syariah/akad': typeof SyariahAkadRoute
  '/syariah/asuransi': typeof SyariahAsuransiRoute
  '/syariah/indeks': typeof SyariahIndeksRoute
  '/syariah/terlarang': typeof SyariahTerlarangRoute
  '/portal': typeof PortalIndexRoute
  '/syariah': typeof SyariahIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/100-framework': typeof R100FrameworkRoute
  '/100-komoditas': typeof R100KomoditasRoute
  '/asset': typeof AssetRoute
  '/bookmarks': typeof BookmarksRoute
  '/budget': typeof BudgetRoute
  '/build': typeof BuildRoute
  '/catatan': typeof CatatanRoute
  '/code': typeof CodeRoute
  '/contacts': typeof ContactsRoute
  '/countdown': typeof CountdownRoute
  '/courses': typeof CoursesRoute
  '/design': typeof DesignRoute
  '/development': typeof DevelopmentRoute
  '/digital-assets': typeof DigitalAssetsRoute
  '/earning': typeof EarningRoute
  '/eisenhower': typeof EisenhowerRoute
  '/events': typeof EventsRoute
  '/exams': typeof ExamsRoute
  '/expense': typeof ExpenseRoute
  '/favorit': typeof FavoritRoute
  '/finances': typeof FinancesRoute
  '/financial-health': typeof FinancialHealthRoute
  '/flashcards': typeof FlashcardsRoute
  '/flow': typeof FlowRoute
  '/games': typeof GamesRoute
  '/goals': typeof GoalsRoute
  '/grow': typeof GrowRoute
  '/habits': typeof HabitsRoute
  '/health': typeof HealthRoute
  '/home': typeof HomeRoute
  '/ideas': typeof IdeasRoute
  '/improvement': typeof ImprovementRoute
  '/incoterms': typeof IncotermsRoute
  '/insider': typeof InsiderRoute
  '/insight': typeof InsightRoute
  '/intellectual-property': typeof IntellectualPropertyRoute
  '/inventory': typeof InventoryRoute
  '/investasi': typeof InvestasiRoute
  '/journal': typeof JournalRoute
  '/kalender': typeof KalenderRoute
  '/katalog-produk': typeof KatalogProdukRoute
  '/klien': typeof KlienRouteWithChildren
  '/kredit': typeof KreditRoute
  '/lainnya': typeof LainnyaRoute
  '/languages': typeof LanguagesRoute
  '/legacy': typeof LegacyRoute
  '/liability': typeof LiabilityRoute
  '/liquid-reserves': typeof LiquidReservesRoute
  '/movies': typeof MoviesRoute
  '/music': typeof MusicRoute
  '/notes': typeof NotesRoute
  '/outlook': typeof OutlookRoute
  '/outward': typeof OutwardRoute
  '/pajak': typeof PajakRoute
  '/paper-securities': typeof PaperSecuritiesRoute
  '/passwords': typeof PasswordsRoute
  '/photography': typeof PhotographyRoute
  '/physical-commodities': typeof PhysicalCommoditiesRoute
  '/pocket': typeof PocketRoute
  '/podcasts': typeof PodcastsRoute
  '/pomodoro': typeof PomodoroRoute
  '/portal': typeof PortalRouteWithChildren
  '/pouch': typeof PouchRoute
  '/profil': typeof ProfilRoute
  '/proyek': typeof ProyekRoute
  '/proyek-personal': typeof ProyekPersonalRoute
  '/reading': typeof ReadingRoute
  '/real-estate': typeof RealEstateRoute
  '/recipes': typeof RecipesRoute
  '/reliance': typeof RelianceRoute
  '/shopping': typeof ShoppingRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/sufficent': typeof SufficentRoute
  '/surety': typeof SuretyRoute
  '/swot': typeof SwotRoute
  '/task-manager': typeof TaskManagerRoute
  '/terminal': typeof TerminalRoute
  '/trips': typeof TripsRoute
  '/trunk': typeof TrunkRoute
  '/tugas': typeof TugasRoute
  '/valuasi': typeof ValuasiRoute
  '/vault': typeof VaultRoute
  '/wallet': typeof WalletRoute
  '/water': typeof WaterRoute
  '/weather': typeof WeatherRoute
  '/workouts': typeof WorkoutsRoute
  '/writing': typeof WritingRoute
  '/zakat': typeof ZakatRoute
  '/klien/$clientId': typeof KlienClientIdRoute
  '/kurasi/$slug': typeof KurasiSlugRoute
  '/portal/dokumen': typeof PortalDokumenRoute
  '/portal/jadwal': typeof PortalJadwalRoute
  '/portal/pesan': typeof PortalPesanRoute
  '/portal/progres': typeof PortalProgresRoute
  '/syariah/akad': typeof SyariahAkadRoute
  '/syariah/asuransi': typeof SyariahAsuransiRoute
  '/syariah/indeks': typeof SyariahIndeksRoute
  '/syariah/terlarang': typeof SyariahTerlarangRoute
  '/portal/': typeof PortalIndexRoute
  '/syariah/': typeof SyariahIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/100-framework'
    | '/100-komoditas'
    | '/asset'
    | '/bookmarks'
    | '/budget'
    | '/build'
    | '/catatan'
    | '/code'
    | '/contacts'
    | '/countdown'
    | '/courses'
    | '/design'
    | '/development'
    | '/digital-assets'
    | '/earning'
    | '/eisenhower'
    | '/events'
    | '/exams'
    | '/expense'
    | '/favorit'
    | '/finances'
    | '/financial-health'
    | '/flashcards'
    | '/flow'
    | '/games'
    | '/goals'
    | '/grow'
    | '/habits'
    | '/health'
    | '/home'
    | '/ideas'
    | '/improvement'
    | '/incoterms'
    | '/insider'
    | '/insight'
    | '/intellectual-property'
    | '/inventory'
    | '/investasi'
    | '/journal'
    | '/kalender'
    | '/katalog-produk'
    | '/klien'
    | '/kredit'
    | '/lainnya'
    | '/languages'
    | '/legacy'
    | '/liability'
    | '/liquid-reserves'
    | '/movies'
    | '/music'
    | '/notes'
    | '/outlook'
    | '/outward'
    | '/pajak'
    | '/paper-securities'
    | '/passwords'
    | '/photography'
    | '/physical-commodities'
    | '/pocket'
    | '/podcasts'
    | '/pomodoro'
    | '/portal'
    | '/pouch'
    | '/profil'
    | '/proyek'
    | '/proyek-personal'
    | '/reading'
    | '/real-estate'
    | '/recipes'
    | '/reliance'
    | '/shopping'
    | '/subscriptions'
    | '/sufficent'
    | '/surety'
    | '/swot'
    | '/task-manager'
    | '/terminal'
    | '/trips'
    | '/trunk'
    | '/tugas'
    | '/valuasi'
    | '/vault'
    | '/wallet'
    | '/water'
    | '/weather'
    | '/workouts'
    | '/writing'
    | '/zakat'
    | '/klien/$clientId'
    | '/kurasi/$slug'
    | '/portal/dokumen'
    | '/portal/jadwal'
    | '/portal/pesan'
    | '/portal/progres'
    | '/syariah/akad'
    | '/syariah/asuransi'
    | '/syariah/indeks'
    | '/syariah/terlarang'
    | '/portal/'
    | '/syariah/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/100-framework'
    | '/100-komoditas'
    | '/asset'
    | '/bookmarks'
    | '/budget'
    | '/build'
    | '/catatan'
    | '/code'
    | '/contacts'
    | '/countdown'
    | '/courses'
    | '/design'
    | '/development'
    | '/digital-assets'
    | '/earning'
    | '/eisenhower'
    | '/events'
    | '/exams'
    | '/expense'
    | '/favorit'
    | '/finances'
    | '/financial-health'
    | '/flashcards'
    | '/flow'
    | '/games'
    | '/goals'
    | '/grow'
    | '/habits'
    | '/health'
    | '/home'
    | '/ideas'
    | '/improvement'
    | '/incoterms'
    | '/insider'
    | '/insight'
    | '/intellectual-property'
    | '/inventory'
    | '/investasi'
    | '/journal'
    | '/kalender'
    | '/katalog-produk'
    | '/klien'
    | '/kredit'
    | '/lainnya'
    | '/languages'
    | '/legacy'
    | '/liability'
    | '/liquid-reserves'
    | '/movies'
    | '/music'
    | '/notes'
    | '/outlook'
    | '/outward'
    | '/pajak'
    | '/paper-securities'
    | '/passwords'
    | '/photography'
    | '/physical-commodities'
    | '/pocket'
    | '/podcasts'
    | '/pomodoro'
    | '/pouch'
    | '/profil'
    | '/proyek'
    | '/proyek-personal'
    | '/reading'
    | '/real-estate'
    | '/recipes'
    | '/reliance'
    | '/shopping'
    | '/subscriptions'
    | '/sufficent'
    | '/surety'
    | '/swot'
    | '/task-manager'
    | '/terminal'
    | '/trips'
    | '/trunk'
    | '/tugas'
    | '/valuasi'
    | '/vault'
    | '/wallet'
    | '/water'
    | '/weather'
    | '/workouts'
    | '/writing'
    | '/zakat'
    | '/klien/$clientId'
    | '/kurasi/$slug'
    | '/portal/dokumen'
    | '/portal/jadwal'
    | '/portal/pesan'
    | '/portal/progres'
    | '/syariah/akad'
    | '/syariah/asuransi'
    | '/syariah/indeks'
    | '/syariah/terlarang'
    | '/portal'
    | '/syariah'
  id:
    | '__root__'
    | '/'
    | '/100-framework'
    | '/100-komoditas'
    | '/asset'
    | '/bookmarks'
    | '/budget'
    | '/build'
    | '/catatan'
    | '/code'
    | '/contacts'
    | '/countdown'
    | '/courses'
    | '/design'
    | '/development'
    | '/digital-assets'
    | '/earning'
    | '/eisenhower'
    | '/events'
    | '/exams'
    | '/expense'
    | '/favorit'
    | '/finances'
    | '/financial-health'
    | '/flashcards'
    | '/flow'
    | '/games'
    | '/goals'
    | '/grow'
    | '/habits'
    | '/health'
    | '/home'
    | '/ideas'
    | '/improvement'
    | '/incoterms'
    | '/insider'
    | '/insight'
    | '/intellectual-property'
    | '/inventory'
    | '/investasi'
    | '/journal'
    | '/kalender'
    | '/katalog-produk'
    | '/klien'
    | '/kredit'
    | '/lainnya'
    | '/languages'
    | '/legacy'
    | '/liability'
    | '/liquid-reserves'
    | '/movies'
    | '/music'
    | '/notes'
    | '/outlook'
    | '/outward'
    | '/pajak'
    | '/paper-securities'
    | '/passwords'
    | '/photography'
    | '/physical-commodities'
    | '/pocket'
    | '/podcasts'
    | '/pomodoro'
    | '/portal'
    | '/pouch'
    | '/profil'
    | '/proyek'
    | '/proyek-personal'
    | '/reading'
    | '/real-estate'
    | '/recipes'
    | '/reliance'
    | '/shopping'
    | '/subscriptions'
    | '/sufficent'
    | '/surety'
    | '/swot'
    | '/task-manager'
    | '/terminal'
    | '/trips'
    | '/trunk'
    | '/tugas'
    | '/valuasi'
    | '/vault'
    | '/wallet'
    | '/water'
    | '/weather'
    | '/workouts'
    | '/writing'
    | '/zakat'
    | '/klien/$clientId'
    | '/kurasi/$slug'
    | '/portal/dokumen'
    | '/portal/jadwal'
    | '/portal/pesan'
    | '/portal/progres'
    | '/syariah/akad'
    | '/syariah/asuransi'
    | '/syariah/indeks'
    | '/syariah/terlarang'
    | '/portal/'
    | '/syariah/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R100FrameworkRoute: typeof R100FrameworkRoute
  R100KomoditasRoute: typeof R100KomoditasRoute
  AssetRoute: typeof AssetRoute
  BookmarksRoute: typeof BookmarksRoute
  BudgetRoute: typeof BudgetRoute
  BuildRoute: typeof BuildRoute
  CatatanRoute: typeof CatatanRoute
  CodeRoute: typeof CodeRoute
  ContactsRoute: typeof ContactsRoute
  CountdownRoute: typeof CountdownRoute
  CoursesRoute: typeof CoursesRoute
  DesignRoute: typeof DesignRoute
  DevelopmentRoute: typeof DevelopmentRoute
  DigitalAssetsRoute: typeof DigitalAssetsRoute
  EarningRoute: typeof EarningRoute
  EisenhowerRoute: typeof EisenhowerRoute
  EventsRoute: typeof EventsRoute
  ExamsRoute: typeof ExamsRoute
  ExpenseRoute: typeof ExpenseRoute
  FavoritRoute: typeof FavoritRoute
  FinancesRoute: typeof FinancesRoute
  FinancialHealthRoute: typeof FinancialHealthRoute
  FlashcardsRoute: typeof FlashcardsRoute
  FlowRoute: typeof FlowRoute
  GamesRoute: typeof GamesRoute
  GoalsRoute: typeof GoalsRoute
  GrowRoute: typeof GrowRoute
  HabitsRoute: typeof HabitsRoute
  HealthRoute: typeof HealthRoute
  HomeRoute: typeof HomeRoute
  IdeasRoute: typeof IdeasRoute
  ImprovementRoute: typeof ImprovementRoute
  IncotermsRoute: typeof IncotermsRoute
  InsiderRoute: typeof InsiderRoute
  InsightRoute: typeof InsightRoute
  IntellectualPropertyRoute: typeof IntellectualPropertyRoute
  InventoryRoute: typeof InventoryRoute
  InvestasiRoute: typeof InvestasiRoute
  JournalRoute: typeof JournalRoute
  KalenderRoute: typeof KalenderRoute
  KatalogProdukRoute: typeof KatalogProdukRoute
  KlienRoute: typeof KlienRouteWithChildren
  KreditRoute: typeof KreditRoute
  LainnyaRoute: typeof LainnyaRoute
  LanguagesRoute: typeof LanguagesRoute
  LegacyRoute: typeof LegacyRoute
  LiabilityRoute: typeof LiabilityRoute
  LiquidReservesRoute: typeof LiquidReservesRoute
  MoviesRoute: typeof MoviesRoute
  MusicRoute: typeof MusicRoute
  NotesRoute: typeof NotesRoute
  OutlookRoute: typeof OutlookRoute
  OutwardRoute: typeof OutwardRoute
  PajakRoute: typeof PajakRoute
  PaperSecuritiesRoute: typeof PaperSecuritiesRoute
  PasswordsRoute: typeof PasswordsRoute
  PhotographyRoute: typeof PhotographyRoute
  PhysicalCommoditiesRoute: typeof PhysicalCommoditiesRoute
  PocketRoute: typeof PocketRoute
  PodcastsRoute: typeof PodcastsRoute
  PomodoroRoute: typeof PomodoroRoute
  PortalRoute: typeof PortalRouteWithChildren
  PouchRoute: typeof PouchRoute
  ProfilRoute: typeof ProfilRoute
  ProyekRoute: typeof ProyekRoute
  ProyekPersonalRoute: typeof ProyekPersonalRoute
  ReadingRoute: typeof ReadingRoute
  RealEstateRoute: typeof RealEstateRoute
  RecipesRoute: typeof RecipesRoute
  RelianceRoute: typeof RelianceRoute
  ShoppingRoute: typeof ShoppingRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SufficentRoute: typeof SufficentRoute
  SuretyRoute: typeof SuretyRoute
  SwotRoute: typeof SwotRoute
  TaskManagerRoute: typeof TaskManagerRoute
  TerminalRoute: typeof TerminalRoute
  TripsRoute: typeof TripsRoute
  TrunkRoute: typeof TrunkRoute
  TugasRoute: typeof TugasRoute
  ValuasiRoute: typeof ValuasiRoute
  VaultRoute: typeof VaultRoute
  WalletRoute: typeof WalletRoute
  WaterRoute: typeof WaterRoute
  WeatherRoute: typeof WeatherRoute
  WorkoutsRoute: typeof WorkoutsRoute
  WritingRoute: typeof WritingRoute
  ZakatRoute: typeof ZakatRoute
  KurasiSlugRoute: typeof KurasiSlugRoute
  SyariahAkadRoute: typeof SyariahAkadRoute
  SyariahAsuransiRoute: typeof SyariahAsuransiRoute
  SyariahIndeksRoute: typeof SyariahIndeksRoute
  SyariahTerlarangRoute: typeof SyariahTerlarangRoute
  SyariahIndexRoute: typeof SyariahIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/100-framework': {
      id: '/100-framework'
      path: '/100-framework'
      fullPath: '/100-framework'
      preLoaderRoute: typeof R100FrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/100-komoditas': {
      id: '/100-komoditas'
      path: '/100-komoditas'
      fullPath: '/100-komoditas'
      preLoaderRoute: typeof R100KomoditasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset': {
      id: '/asset'
      path: '/asset'
      fullPath: '/asset'
      preLoaderRoute: typeof AssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catatan': {
      id: '/catatan'
      path: '/catatan'
      fullPath: '/catatan'
      preLoaderRoute: typeof CatatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countdown': {
      id: '/countdown'
      path: '/countdown'
      fullPath: '/countdown'
      preLoaderRoute: typeof CountdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-assets': {
      id: '/digital-assets'
      path: '/digital-assets'
      fullPath: '/digital-assets'
      preLoaderRoute: typeof DigitalAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earning': {
      id: '/earning'
      path: '/earning'
      fullPath: '/earning'
      preLoaderRoute: typeof EarningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eisenhower': {
      id: '/eisenhower'
      path: '/eisenhower'
      fullPath: '/eisenhower'
      preLoaderRoute: typeof EisenhowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense': {
      id: '/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof ExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorit': {
      id: '/favorit'
      path: '/favorit'
      fullPath: '/favorit'
      preLoaderRoute: typeof FavoritRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-health': {
      id: '/financial-health'
      path: '/financial-health'
      fullPath: '/financial-health'
      preLoaderRoute: typeof FinancialHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow': {
      id: '/grow'
      path: '/grow'
      fullPath: '/grow'
      preLoaderRoute: typeof GrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/improvement': {
      id: '/improvement'
      path: '/improvement'
      fullPath: '/improvement'
      preLoaderRoute: typeof ImprovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incoterms': {
      id: '/incoterms'
      path: '/incoterms'
      fullPath: '/incoterms'
      preLoaderRoute: typeof IncotermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insider': {
      id: '/insider'
      path: '/insider'
      fullPath: '/insider'
      preLoaderRoute: typeof InsiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight': {
      id: '/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof InsightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intellectual-property': {
      id: '/intellectual-property'
      path: '/intellectual-property'
      fullPath: '/intellectual-property'
      preLoaderRoute: typeof IntellectualPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investasi': {
      id: '/investasi'
      path: '/investasi'
      fullPath: '/investasi'
      preLoaderRoute: typeof InvestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog-produk': {
      id: '/katalog-produk'
      path: '/katalog-produk'
      fullPath: '/katalog-produk'
      preLoaderRoute: typeof KatalogProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klien': {
      id: '/klien'
      path: '/klien'
      fullPath: '/klien'
      preLoaderRoute: typeof KlienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kredit': {
      id: '/kredit'
      path: '/kredit'
      fullPath: '/kredit'
      preLoaderRoute: typeof KreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lainnya': {
      id: '/lainnya'
      path: '/lainnya'
      fullPath: '/lainnya'
      preLoaderRoute: typeof LainnyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liability': {
      id: '/liability'
      path: '/liability'
      fullPath: '/liability'
      preLoaderRoute: typeof LiabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquid-reserves': {
      id: '/liquid-reserves'
      path: '/liquid-reserves'
      fullPath: '/liquid-reserves'
      preLoaderRoute: typeof LiquidReservesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlook': {
      id: '/outlook'
      path: '/outlook'
      fullPath: '/outlook'
      preLoaderRoute: typeof OutlookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outward': {
      id: '/outward'
      path: '/outward'
      fullPath: '/outward'
      preLoaderRoute: typeof OutwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pajak': {
      id: '/pajak'
      path: '/pajak'
      fullPath: '/pajak'
      preLoaderRoute: typeof PajakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper-securities': {
      id: '/paper-securities'
      path: '/paper-securities'
      fullPath: '/paper-securities'
      preLoaderRoute: typeof PaperSecuritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwords': {
      id: '/passwords'
      path: '/passwords'
      fullPath: '/passwords'
      preLoaderRoute: typeof PasswordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-commodities': {
      id: '/physical-commodities'
      path: '/physical-commodities'
      fullPath: '/physical-commodities'
      preLoaderRoute: typeof PhysicalCommoditiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pocket': {
      id: '/pocket'
      path: '/pocket'
      fullPath: '/pocket'
      preLoaderRoute: typeof PocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomodoro': {
      id: '/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof PomodoroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pouch': {
      id: '/pouch'
      path: '/pouch'
      fullPath: '/pouch'
      preLoaderRoute: typeof PouchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyek': {
      id: '/proyek'
      path: '/proyek'
      fullPath: '/proyek'
      preLoaderRoute: typeof ProyekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyek-personal': {
      id: '/proyek-personal'
      path: '/proyek-personal'
      fullPath: '/proyek-personal'
      preLoaderRoute: typeof ProyekPersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reliance': {
      id: '/reliance'
      path: '/reliance'
      fullPath: '/reliance'
      preLoaderRoute: typeof RelianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sufficent': {
      id: '/sufficent'
      path: '/sufficent'
      fullPath: '/sufficent'
      preLoaderRoute: typeof SufficentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surety': {
      id: '/surety'
      path: '/surety'
      fullPath: '/surety'
      preLoaderRoute: typeof SuretyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swot': {
      id: '/swot'
      path: '/swot'
      fullPath: '/swot'
      preLoaderRoute: typeof SwotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-manager': {
      id: '/task-manager'
      path: '/task-manager'
      fullPath: '/task-manager'
      preLoaderRoute: typeof TaskManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trunk': {
      id: '/trunk'
      path: '/trunk'
      fullPath: '/trunk'
      preLoaderRoute: typeof TrunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tugas': {
      id: '/tugas'
      path: '/tugas'
      fullPath: '/tugas'
      preLoaderRoute: typeof TugasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valuasi': {
      id: '/valuasi'
      path: '/valuasi'
      fullPath: '/valuasi'
      preLoaderRoute: typeof ValuasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water': {
      id: '/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof WaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zakat': {
      id: '/zakat'
      path: '/zakat'
      fullPath: '/zakat'
      preLoaderRoute: typeof ZakatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klien/$clientId': {
      id: '/klien/$clientId'
      path: '/$clientId'
      fullPath: '/klien/$clientId'
      preLoaderRoute: typeof KlienClientIdRouteImport
      parentRoute: typeof KlienRoute
    }
    '/kurasi/$slug': {
      id: '/kurasi/$slug'
      path: '/kurasi/$slug'
      fullPath: '/kurasi/$slug'
      preLoaderRoute: typeof KurasiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dokumen': {
      id: '/portal/dokumen'
      path: '/dokumen'
      fullPath: '/portal/dokumen'
      preLoaderRoute: typeof PortalDokumenRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/jadwal': {
      id: '/portal/jadwal'
      path: '/jadwal'
      fullPath: '/portal/jadwal'
      preLoaderRoute: typeof PortalJadwalRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/pesan': {
      id: '/portal/pesan'
      path: '/pesan'
      fullPath: '/portal/pesan'
      preLoaderRoute: typeof PortalPesanRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/progres': {
      id: '/portal/progres'
      path: '/progres'
      fullPath: '/portal/progres'
      preLoaderRoute: typeof PortalProgresRouteImport
      parentRoute: typeof PortalRoute
    }
    '/syariah/': {
      id: '/syariah/'
      path: '/syariah'
      fullPath: '/syariah/'
      preLoaderRoute: typeof SyariahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syariah/akad': {
      id: '/syariah/akad'
      path: '/syariah/akad'
      fullPath: '/syariah/akad'
      preLoaderRoute: typeof SyariahAkadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syariah/asuransi': {
      id: '/syariah/asuransi'
      path: '/syariah/asuransi'
      fullPath: '/syariah/asuransi'
      preLoaderRoute: typeof SyariahAsuransiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syariah/indeks': {
      id: '/syariah/indeks'
      path: '/syariah/indeks'
      fullPath: '/syariah/indeks'
      preLoaderRoute: typeof SyariahIndeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syariah/terlarang': {
      id: '/syariah/terlarang'
      path: '/syariah/terlarang'
      fullPath: '/syariah/terlarang'
      preLoaderRoute: typeof SyariahTerlarangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KlienRouteChildren {
  KlienClientIdRoute: typeof KlienClientIdRoute
}

const KlienRouteChildren: KlienRouteChildren = {
  KlienClientIdRoute: KlienClientIdRoute,
}

const KlienRouteWithChildren = KlienRoute._addFileChildren(KlienRouteChildren)

interface PortalRouteChildren {
  PortalDokumenRoute: typeof PortalDokumenRoute
  PortalJadwalRoute: typeof PortalJadwalRoute
  PortalPesanRoute: typeof PortalPesanRoute
  PortalProgresRoute: typeof PortalProgresRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDokumenRoute: PortalDokumenRoute,
  PortalJadwalRoute: PortalJadwalRoute,
  PortalPesanRoute: PortalPesanRoute,
  PortalProgresRoute: PortalProgresRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R100FrameworkRoute: R100FrameworkRoute,
  R100KomoditasRoute: R100KomoditasRoute,
  AssetRoute: AssetRoute,
  BookmarksRoute: BookmarksRoute,
  BudgetRoute: BudgetRoute,
  BuildRoute: BuildRoute,
  CatatanRoute: CatatanRoute,
  CodeRoute: CodeRoute,
  ContactsRoute: ContactsRoute,
  CountdownRoute: CountdownRoute,
  CoursesRoute: CoursesRoute,
  DesignRoute: DesignRoute,
  DevelopmentRoute: DevelopmentRoute,
  DigitalAssetsRoute: DigitalAssetsRoute,
  EarningRoute: EarningRoute,
  EisenhowerRoute: EisenhowerRoute,
  EventsRoute: EventsRoute,
  ExamsRoute: ExamsRoute,
  ExpenseRoute: ExpenseRoute,
  FavoritRoute: FavoritRoute,
  FinancesRoute: FinancesRoute,
  FinancialHealthRoute: FinancialHealthRoute,
  FlashcardsRoute: FlashcardsRoute,
  FlowRoute: FlowRoute,
  GamesRoute: GamesRoute,
  GoalsRoute: GoalsRoute,
  GrowRoute: GrowRoute,
  HabitsRoute: HabitsRoute,
  HealthRoute: HealthRoute,
  HomeRoute: HomeRoute,
  IdeasRoute: IdeasRoute,
  ImprovementRoute: ImprovementRoute,
  IncotermsRoute: IncotermsRoute,
  InsiderRoute: InsiderRoute,
  InsightRoute: InsightRoute,
  IntellectualPropertyRoute: IntellectualPropertyRoute,
  InventoryRoute: InventoryRoute,
  InvestasiRoute: InvestasiRoute,
  JournalRoute: JournalRoute,
  KalenderRoute: KalenderRoute,
  KatalogProdukRoute: KatalogProdukRoute,
  KlienRoute: KlienRouteWithChildren,
  KreditRoute: KreditRoute,
  LainnyaRoute: LainnyaRoute,
  LanguagesRoute: LanguagesRoute,
  LegacyRoute: LegacyRoute,
  LiabilityRoute: LiabilityRoute,
  LiquidReservesRoute: LiquidReservesRoute,
  MoviesRoute: MoviesRoute,
  MusicRoute: MusicRoute,
  NotesRoute: NotesRoute,
  OutlookRoute: OutlookRoute,
  OutwardRoute: OutwardRoute,
  PajakRoute: PajakRoute,
  PaperSecuritiesRoute: PaperSecuritiesRoute,
  PasswordsRoute: PasswordsRoute,
  PhotographyRoute: PhotographyRoute,
  PhysicalCommoditiesRoute: PhysicalCommoditiesRoute,
  PocketRoute: PocketRoute,
  PodcastsRoute: PodcastsRoute,
  PomodoroRoute: PomodoroRoute,
  PortalRoute: PortalRouteWithChildren,
  PouchRoute: PouchRoute,
  ProfilRoute: ProfilRoute,
  ProyekRoute: ProyekRoute,
  ProyekPersonalRoute: ProyekPersonalRoute,
  ReadingRoute: ReadingRoute,
  RealEstateRoute: RealEstateRoute,
  RecipesRoute: RecipesRoute,
  RelianceRoute: RelianceRoute,
  ShoppingRoute: ShoppingRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SufficentRoute: SufficentRoute,
  SuretyRoute: SuretyRoute,
  SwotRoute: SwotRoute,
  TaskManagerRoute: TaskManagerRoute,
  TerminalRoute: TerminalRoute,
  TripsRoute: TripsRoute,
  TrunkRoute: TrunkRoute,
  TugasRoute: TugasRoute,
  ValuasiRoute: ValuasiRoute,
  VaultRoute: VaultRoute,
  WalletRoute: WalletRoute,
  WaterRoute: WaterRoute,
  WeatherRoute: WeatherRoute,
  WorkoutsRoute: WorkoutsRoute,
  WritingRoute: WritingRoute,
  ZakatRoute: ZakatRoute,
  KurasiSlugRoute: KurasiSlugRoute,
  SyariahAkadRoute: SyariahAkadRoute,
  SyariahAsuransiRoute: SyariahAsuransiRoute,
  SyariahIndeksRoute: SyariahIndeksRoute,
  SyariahTerlarangRoute: SyariahTerlarangRoute,
  SyariahIndexRoute: SyariahIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
