import {
  LayoutDashboard,
  Users,
  FolderKanban,
  CheckSquare,
  CheckCircle2,
  Sparkles,
  NotebookText,
  CalendarDays,
  Compass,
  Gauge,
  MessagesSquare,
  CalendarClock,
  FolderOpen,
  Activity,
  LineChart,
  AlertTriangle,
  FileText,
  Shield,
  Calculator,
  HeartHandshake,
  Navigation,
  Building,
  TrendingUp,
  Package,
  Grid2X2,
  MoreHorizontal,
  Star,
  User,
  Settings,
  Wallet,
  CreditCard,
  ChevronDown,
  ChevronRight,
  Droplet,
  Timer,
  Briefcase,
  Target,
  BookOpen,
  Bookmark,
  Lightbulb,
  Eye,
  Key,
  Dumbbell,
  Utensils,
  Music,
  CloudSun,
  Book,
  Plane,
  ShoppingCart,
  Heart,
  HeartPulse,
  Archive,
  GraduationCap,
  Layers,
  FileCheck,
  Globe,
  Film,
  Gamepad2,
  Podcast,
  Ticket,
  PenTool,
  Camera,
  Type,
  Code,
  DollarSign,
  ShieldCheck,
  RefreshCw,
  Building2,
  Sprout,
  Search,
  Bell,
  Coins,
  MessageCircle,
  Truck,
  Store,
  Home,
  ScrollText,
  Binary,
  Info,
  type LucideIcon,
} from "lucide-react";

export type NavItem = {
  to: string;
  label: string;
  icon: LucideIcon;
};

export type NavGroup = {
  title: string;
  items: NavItem[];
};

export const navKonsultan: NavGroup[] = [
  {
    title: "100 Things",
    items: [
      { to: "/100-framework", label: "100 Framework", icon: Grid2X2 },
      { to: "/100-komoditas", label: "100 Komoditas", icon: Package },
    ],
  },
  {
    title: "Tahapan",
    items: [
      { to: "/reliance", label: "Reliance", icon: ShieldCheck },
      { to: "/sufficent", label: "Sufficent", icon: CheckCircle2 },
      { to: "/improvement", label: "Improvement", icon: TrendingUp },
      { to: "/development", label: "Development", icon: Sparkles },
    ],
  },
  {
    title: "Proyek",
    items: [
      { to: "/projects", label: "Daftar Proyek", icon: FolderKanban },
      { to: "/clients", label: "Klien & Kontak", icon: Users },
      { to: "/reports", label: "Laporan Khusus", icon: NotebookText },
    ],
  },
  {
    title: "Overview",
    items: [
      { to: "/", label: "Dashboard", icon: LayoutDashboard },
      { to: "/insider", label: "Insider", icon: Eye },
      { to: "/insight", label: "Insight", icon: Lightbulb },
      { to: "/outward", label: "Outward", icon: Compass },
      { to: "/outlook", label: "Outlook", icon: TrendingUp },
      { to: "/bookmarks", label: "Bookmarks", icon: Bookmark },
      { to: "/events", label: "Events", icon: Ticket },
      { to: "/weather", label: "Weather", icon: CloudSun },
    ],
  },
  {
    title: "Productivity",
    items: [
      { to: "/task-manager", label: "Task Manager", icon: CheckSquare },
      { to: "/pomodoro", label: "Pomodoro Timer", icon: Timer },
      { to: "/eisenhower", label: "Eisenhower Matrix", icon: Grid2X2 },
      { to: "/incoterms", label: "Panduan Incoterms", icon: Navigation },
      { to: "/tasks-calendar", label: "Tasks Calendar & Timeline", icon: CalendarClock },
    ],
  },
  {
    title: "Portal Klien",
    items: [
      { to: "/portal", label: "Ringkasan", icon: LayoutDashboard },
      { to: "/portal/progres", label: "Progres", icon: Gauge },
      { to: "/portal/pesan", label: "Pesan", icon: MessagesSquare },
      { to: "/portal/jadwal", label: "Jadwal", icon: CalendarClock },
      { to: "/portal/dokumen", label: "Dokumen", icon: FolderOpen },
    ],
  },
  {
    title: "Asset",
    items: [
      { to: "/asset", label: "Kuadran Aset", icon: Briefcase },
      { to: "/liquid-reserves", label: "Liquid Reserves", icon: Coins },
      { to: "/physical-commodities", label: "Physical Commodities", icon: Package },
      { to: "/real-estate", label: "Real Estate", icon: Home },
      { to: "/paper-securities", label: "Paper Securities", icon: ScrollText },
      { to: "/digital-assets", label: "Digital Assets", icon: Binary },
      { to: "/intellectual-property", label: "Intellectual Property", icon: Lightbulb },
    ],
  },
  {
    title: "Liability",
    items: [{ to: "/liability", label: "Kuadran Liabilitas", icon: CreditCard }],
  },
  {
    title: "Earning",
    items: [{ to: "/earning", label: "Kuadran Pendapatan", icon: DollarSign }],
  },
  {
    title: "Expense",
    items: [{ to: "/expense", label: "Kuadran Pengeluaran", icon: ShoppingCart }],
  },
  {
    title: "5 Tahap Keuangan",
    items: [
      { to: "/surety", label: "Tahap 1: Surety", icon: ShieldCheck },
      { to: "/flow", label: "Tahap 2: Flow", icon: RefreshCw },
      { to: "/build", label: "Tahap 3: Build", icon: Building2 },
      { to: "/grow", label: "Tahap 4: Grow", icon: Sprout },
      { to: "/legacy", label: "Tahap 5: Legacy", icon: BookOpen },
    ],
  },
  {
    title: "Value Treated",
    items: [
      { to: "/kurasi/ekonomi", label: "Ekonomi", icon: Coins },
      { to: "/kurasi/statistik", label: "Statistik", icon: LineChart },
      { to: "/kurasi/manajemen", label: "Manajemen", icon: Briefcase },
      { to: "/kurasi/komunikasi", label: "Komunikasi", icon: MessageCircle },
      { to: "/kurasi/logistik", label: "Logistik", icon: Truck },
      { to: "/kurasi/bisnis", label: "Bisnis", icon: Store },
      { to: "/kurasi/administrasi", label: "Administrasi", icon: FileText },
      { to: "/kurasi/akuntansi", label: "Akuntansi", icon: Calculator },
      { to: "/kurasi/asuransi", label: "Asuransi", icon: Shield },
      { to: "/kurasi/investasi", label: "Investasi", icon: TrendingUp },
      { to: "/swot", label: "SWOT Analysis", icon: Target },
    ],
  },
  {
    title: "Keuangan & Investasi",
    items: [
      { to: "/finances", label: "Finances", icon: DollarSign },
      { to: "/budget", label: "Budget", icon: Wallet },
      { to: "/kredit", label: "Kredit & Utang", icon: CreditCard },
      { to: "/subscriptions", label: "Subscriptions", icon: CreditCard },
      { to: "/pajak", label: "Kalkulator Pajak", icon: Calculator },
      { to: "/investasi", label: "Kalkulator Investasi", icon: TrendingUp },
      { to: "/valuasi", label: "Valuasi MAPPI", icon: Building },
      { to: "/financial-health", label: "Kesehatan Finansial", icon: HeartPulse },
    ],
  },
  {
    title: "Syariah & Muamalah",
    items: [
      { to: "/syariah", label: "Fiqih Muamalah", icon: HeartHandshake },
      { to: "/zakat", label: "Kalkulator Zakat", icon: Calculator },
    ],
  },
  {
    title: "Lain-lain",
    items: [
      { to: "/kalkulator", label: "Kalkulator Umum", icon: Calculator },
      { to: "/water", label: "Water Tracker", icon: Droplet },
    ],
  },
];
